#include "support/src-defs.h"
#undef CMN_ARCH
#undef CMN_MAX_NUM_OPERANDS
//#undef CMN_FALLBACK
#undef cmn_iseq_convert_pcs_to_inums
#undef cmn_iseq_rename_abs_inums_using_map
#undef cmn_iseq_rename_sboxed_abs_inums_using_map
#undef cmn_iseq_rename_abs_inum_tags_using_map
#undef cmn_iseq_convert_abs_inums_to_pcrel_inums
#undef cmn_iseq_convert_sboxed_abs_inums_to_pcrel_inums
#undef cmn_iseq_convert_sboxed_abs_inums_to_binpcrel_inums
#undef cmn_iseq_convert_abs_inum_tags_to_pcrel_inums
#undef cmn_iseq_convert_pcrel_inums_to_abs_inums
#undef cmn_iseq_eliminate_nops
#undef cmn_iseq_canonicalize_jump_targets
#undef cmn_insn_put_nop
#undef cmn_insn_is_nop
#undef cmn_insn_copy
#undef cmn_iseq_copy
#undef cmn_insn_t
#undef cmn_iseq_to_string
#undef cmn_insn_is_indirect_branch
#undef cmn_insn_get_pcrel_values
#undef cmn_insn_set_pcrel_values
#undef cmn_insn_get_pcrel_operands
#undef cmn_gen_sym_exec_db
#undef cmn_gen_sym_exec_reader_file
#undef cmn_gen_sym_exec_reader_file_entry_for_insn
#undef cmn_gen_insn_usedef_db
#undef cmn_gen_insn_types_db
#undef cmn_get_usedef_using_transfer_function
//#undef cmn_get_type_constraints_using_transfer_function
#undef cmn_get_type_transfers_using_transfer_function
#undef cmn_insn_list_elem_t
#undef cmn_insn_add_memtouch_variants_to_list
#undef cmn_insn_add_nop_insn_to_list
#undef cmn_read_insn_list_from_file
#undef cmn_insn_list_free
#undef cmn_insn_fetch_raw
#undef cmn_get_transfer_state_str
#undef cmn_insn_arg
#undef cmn_insn_to_int_array
#undef cmn_cpp_insn_to_string
//#undef cmn_apply_transfer_fun
//#undef cmn_iseq_matches_template_var
#undef cmn_get_labels_rec
#undef cmn_get_labels
#undef cmn_get_loop_heads_rec
#undef cmn_get_loop_heads
#undef cmn_get_next_pc_pred_states
#undef cmn_get_successors
#undef cmn_get_tfg_from_db_iterator
#undef cmn_insn_get_tfg_matching_at_iter
#undef cmn_insn_get_next_matching_iterator
#undef cmn_get_tfg
#undef cmn_get_tfg_full
#undef cmn_insn_get_tfg
#undef cmn_m_db
#undef cmn_iseq_from_string
#undef cmn_add
#undef cmn_parse_sym_exec_db
#undef cmn_sym_exec_db_filename
#undef cmn_get_fresh_state_str
#undef cmn_insn_is_function_call
#undef cmn_get_base_state
#undef cmn_m_base_state
#undef cmn_ulong
#undef cmn_is_src
#undef cmn_print_usedef_mismatch
#undef cmn_insn_get_usedef
#undef cmn_insn_get_usedef_regs
#undef cmn_iseq_get_usedef
#undef cmn_iseq_get_usedef_regs
#undef cmn_insn_find_usedef_tab_entry
#undef cmn_insn_type_signature_supported
#undef cmn_iseq_canonicalize
#undef cmn_insn_canonicalize
#undef cmn_iseq_eliminate_nops
#undef cmn_iseq_strict_canonicalize_helper
#undef cmn_iseq_strict_canonicalize_regs
#undef cmn_operand_strict_canonicalize_regs
#undef cmn_operand_strict_canonicalize_imms
#undef cmn_memtouch_strict_canonicalize
#undef cmn_infer_regcons_from_assembly
//#undef cmn_peep_preprocess_using_regmap
#undef cmn_iseq_disassemble
#undef cmn_iseq_disassemble_with_bin_offsets
#undef cmn_iseq_inv_rename
#undef cmn_insn_disassemble
#undef cmn_insn_add_to_pcrels
#undef cmn_insn_inv_rename_registers
#undef cmn_insn_inv_rename_memory_operands
#undef cmn_insn_inv_rename_constants
#undef cmn_assemble
#undef cmn_exregname_suffix
//#undef cmn_fingerprintdb_elem_t
//#undef cmn_fingerprintdb_init
//#undef cmn_fingerprintdb_free
//#undef cmn_fingerprintdb_elem_free
//#undef cmn_fingerprintdb_to_string
//#undef cmn_fingerprintdb_add_variants
//#undef cmn_fingerprintdb_add_from_fp
//#undef cmn_fingerprintdb_add_from_string
//#undef cmn_fingerprintdb_is_empty
//#undef cmn_fingerprintdb_to_string
#undef cmn_iseq_compute_fingerprint
#undef fscanf_harvest_output_cmn
//#undef cmn_fingerprintdb_search_for_matching_comment
#undef cmn_iseq_matches_with_symbols
#undef cmn_insn_symbols_are_contained_in_map
#undef map_symbols_are_contained_in_cmn_iseq
#undef symbol_is_contained_in_cmn_insn
//#undef cmn_harvested_iseq_to_string
#undef cmn_iseq_hash_func_after_canon
#undef cmn_iseq_hash_canonicalize
#undef cmn_iseq_hash_func
#undef cmn_insn_hash_canonicalize
#undef cmn_iseq_canonicalize_symbols
#undef cmn_iseq_canonicalize_locals
#undef cmn_iseq_canonicalize_locals_symbols
#undef cmn_insn_canonicalize_locals_symbols
#undef cmn_iseq_fill_memtouchs
#undef cmn_insn_add_memtouch
#undef cmn_insn_add_call_arg
#undef cmn_insn_add_memtouch_elem
#undef cmn_m_db_ro_entries
#undef CMN_M_DB_RO_NUM_ENTRIES_STR
#undef cmn_insn_gen_sym_exec_reader_file
#undef cmn_m_db_file
#undef cmn_insn_is_unconditional_branch_not_fcall
#undef cmn_insn_is_function_return
#undef cmn_insn_put_jump_to_nextpc
#undef cmn_insn_put_jump_to_pcrel
#undef cmn_strict_canonicalization_state_t
#undef cmn_insn_get_max_num_imm_operands
#undef cmn_iseq_strict_canonicalize
#undef cmn_insn_exists_in_list
#undef cmn_insns_equal
#undef cmn_pc_get_function_name_and_insn_num
#undef cmn_regset_truncate_masks_based_on_reg_sizes_in_insn
#undef cmn_insn_get_size_for_exreg
#undef cmn_iseq_rename_nextpcs
#undef cmn_insn_rename_nextpcs
#undef cmn_prefix
#undef cmn_insn_get_tfg_from_insn_db_match
#undef cmn_get_tfg_from_insn_db_list_elem
#undef cmn_usedef_tab_init
#undef cmn_usedef_tab_read_from_file
#undef cmn_usedef_db_read
#undef cmn_ts_tab_read_from_file
#undef cmn_types_db_read
#undef usedef_tab_cmn
#undef cmn_ts_tab_init
#undef ts_tab_cmn
#undef cmn_insn_find_ts_tab_entry
#undef cmn_iseq_serialize
#undef cmn_iseq_deserialize

#if CMN == COMMON_SRC
#define CMN_ARCH ARCH_SRC
#define CMN_MAX_NUM_OPERANDS SRC_MAX_NUM_OPERANDS
//#define CMN_FALLBACK SRC_FALLBACK
#define cmn_iseq_convert_pcs_to_inums src_iseq_convert_pcs_to_inums
#define cmn_iseq_rename_abs_inums_using_map src_iseq_rename_abs_inums_using_map
#define cmn_iseq_rename_sboxed_abs_inums_using_map src_iseq_rename_sboxed_abs_inums_using_map
#define cmn_iseq_rename_abs_inum_tags_using_map src_iseq_rename_abs_inum_tags_using_map
#define cmn_iseq_convert_abs_inums_to_pcrel_inums src_iseq_convert_abs_inums_to_pcrel_inums
#define cmn_iseq_convert_abs_inums_to_binpcrel_inums src_iseq_convert_abs_inums_to_binpcrel_inums
#define cmn_iseq_convert_sboxed_abs_inums_to_pcrel_inums src_iseq_convert_sboxed_abs_inums_to_pcrel_inums
#define cmn_iseq_convert_abs_inum_tags_to_pcrel_inums src_iseq_convert_abs_inum_tags_to_pcrel_inums
#define cmn_iseq_convert_pcrel_inums_to_abs_inums src_iseq_convert_pcrel_inums_to_abs_inums
#define cmn_iseq_eliminate_nops src_iseq_eliminate_nops
#define cmn_iseq_canonicalize_jump_targets src_iseq_canonicalize_jump_targets
#define cmn_insn_put_nop src_insn_put_nop
#define cmn_insn_is_nop src_insn_is_nop
#define cmn_insn_copy src_insn_copy
#define cmn_iseq_copy src_iseq_copy
#define cmn_insn_t src_insn_t
#define cmn_iseq_to_string src_iseq_to_string
#define cmn_insn_is_indirect_branch src_insn_is_indirect_branch
#define cmn_insn_get_pcrel_values src_insn_get_pcrel_values
#define cmn_insn_set_pcrel_values src_insn_set_pcrel_values
#define cmn_insn_get_pcrel_operands src_insn_get_pcrel_operands
#define cmn_gen_sym_exec_db src_gen_sym_exec_db
#define cmn_gen_sym_exec_reader_file src_gen_sym_exec_reader_file
#define cmn_gen_sym_exec_reader_file_entry_for_insn src_gen_sym_exec_reader_file_entry_for_insn
#define cmn_gen_insn_usedef_db src_gen_insn_usedef_db
#define cmn_gen_insn_types_db src_gen_insn_types_db
#define cmn_get_usedef_using_transfer_function src_get_usedef_using_transfer_function
//#define cmn_get_type_constraints_using_transfer_function src_get_type_constraints_using_transfer_function
#define cmn_get_type_transfers_using_transfer_function src_get_type_transfers_using_transfer_function
#define cmn_insn_list_elem_t src_insn_list_elem_t
#define cmn_insn_add_memtouch_variants_to_list src_insn_add_memtouch_variants_to_list
#define cmn_insn_add_nop_insn_to_list src_insn_add_nop_insn_to_list
#define cmn_read_insn_list_from_file src_read_insn_list_from_file
#define cmn_insn_list_free src_insn_list_free
#define cmn_insn_fetch_raw src_insn_fetch_raw
#define cmn_iseq_strict_canonicalize src_iseq_strict_canonicalize
#define cmn_get_transfer_state_str src_get_transfer_state_str
#define cmn_insn_arg src_insn_arg
#define cmn_insn_to_int_array src_insn_to_int_array
#define cmn_cpp_insn_to_string src_cpp_insn_to_string
//#define cmn_apply_transfer_fun src_apply_transfer_fun
//#define cmn_iseq_matches_template_var src_iseq_matches_template_var
#define cmn_get_labels_rec src_get_labels_rec
#define cmn_get_labels src_get_labels
#define cmn_get_loop_heads_rec src_get_loop_heads_rec
#define cmn_get_loop_heads src_get_loop_heads
#define cmn_get_next_pc_pred_states src_get_next_pc_pred_states
#define cmn_get_successors src_get_successors
#define cmn_get_tfg_from_db_iterator src_get_tfg_from_db_iterator
#define cmn_insn_get_tfg_matching_at_iter src_insn_get_tfg_matching_at_iter
#define cmn_insn_get_next_matching_iterator src_insn_get_next_matching_iterator
#define cmn_get_tfg src_get_tfg
#define cmn_get_tfg_full src_get_tfg_full
#define cmn_insn_get_tfg src_insn_get_tfg
#define cmn_m_db src_m_db
#define cmn_add src_add
#define cmn_iseq_from_string src_iseq_from_string
#define cmn_parse_sym_exec_db src_parse_sym_exec_db
#define cmn_sym_exec_db_filename "src_sym_exec_db"
#define cmn_get_fresh_state_str src_get_fresh_state_str
#define cmn_insn_is_function_call src_insn_is_function_call
#define cmn_get_base_state src_get_base_state
#define cmn_m_base_state src_m_base_state
#define cmn_ulong src_ulong
#define cmn_is_src true
#define cmn_print_usedef_mismatch src_print_usedef_mismatch
#define cmn_insn_get_usedef src_insn_get_usedef
#define cmn_insn_get_usedef_regs src_insn_get_usedef_regs
#define cmn_iseq_get_usedef src_iseq_get_usedef
#define cmn_iseq_get_usedef_regs src_iseq_get_usedef_regs
#define cmn_insn_find_usedef_tab_entry src_insn_find_usedef_tab_entry
#define cmn_insn_type_signature_supported src_insn_type_signature_supported
#define cmn_iseq_canonicalize src_iseq_canonicalize
#define cmn_insn_canonicalize src_insn_canonicalize
#define cmn_iseq_eliminate_nops src_iseq_eliminate_nops
#define cmn_iseq_strict_canonicalize_helper src_iseq_strict_canonicalize_helper
#define cmn_iseq_strict_canonicalize_regs src_iseq_strict_canonicalize_regs
#define cmn_operand_strict_canonicalize_regs src_operand_strict_canonicalize_regs
#define cmn_operand_strict_canonicalize_imms src_operand_strict_canonicalize_imms
#define cmn_memtouch_strict_canonicalize src_memtouch_strict_canonicalize
#define cmn_infer_regcons_from_assembly src_infer_regcons_from_assembly
//#define cmn_peep_preprocess_using_regmap src_peep_preprocess_using_regmap
#define cmn_iseq_disassemble src_iseq_disassemble
#define cmn_iseq_disassemble_with_bin_offsets src_iseq_disassemble_with_bin_offsets
#define cmn_iseq_inv_rename src_iseq_inv_rename
#define cmn_insn_disassemble src_insn_disassemble
#define cmn_insn_add_to_pcrels src_insn_add_to_pcrels
#define cmn_insn_inv_rename_registers src_insn_inv_rename_registers
#define cmn_insn_inv_rename_memory_operands src_insn_inv_rename_memory_operands
#define cmn_insn_inv_rename_constants src_insn_inv_rename_constants
#define cmn_assemble src_assemble
#define cmn_exregname_suffix src_exregname_suffix
//#define cmn_fingerprintdb_elem_t src_fingerprintdb_elem_t
//#define cmn_fingerprintdb_elem_t src_fingerprintdb_elem_t
//#define cmn_fingerprintdb_init src_fingerprintdb_init
//#define cmn_fingerprintdb_free src_fingerprintdb_free
//#define cmn_fingerprintdb_elem_free src_fingerprintdb_elem_free
//#define cmn_fingerprintdb_to_string src_fingerprintdb_to_string
//#define cmn_fingerprintdb_add_variants src_fingerprintdb_add_variants
//#define cmn_fingerprintdb_add_from_fp src_fingerprintdb_add_from_fp
//#define cmn_fingerprintdb_add_from_string src_fingerprintdb_add_from_string
//#define cmn_fingerprintdb_is_empty src_fingerprintdb_is_empty
//#define cmn_fingerprintdb_to_string src_fingerprintdb_to_string
#define cmn_iseq_compute_fingerprint src_iseq_compute_fingerprint
#define fscanf_harvest_output_cmn fscanf_harvest_output_src
//#define cmn_fingerprintdb_search_for_matching_comment src_fingerprintdb_search_for_matching_comment
#define cmn_iseq_matches_with_symbols src_iseq_matches_with_symbols
#define cmn_insn_symbols_are_contained_in_map src_insn_symbols_are_contained_in_map
#define map_symbols_are_contained_in_cmn_iseq map_symbols_are_contained_in_src_iseq
#define symbol_is_contained_in_cmn_insn symbol_is_contained_in_src_insn
//#define cmn_harvested_iseq_to_string src_harvested_iseq_to_string
#define cmn_iseq_hash_func_after_canon src_iseq_hash_func_after_canon
#define cmn_iseq_hash_canonicalize src_iseq_hash_canonicalize
#define cmn_iseq_hash_func src_iseq_hash_func
#define cmn_insn_hash_canonicalize src_insn_hash_canonicalize
#define cmn_iseq_canonicalize_symbols src_iseq_canonicalize_symbols
#define cmn_iseq_canonicalize_locals src_iseq_canonicalize_locals
#define cmn_iseq_canonicalize_locals_symbols src_iseq_canonicalize_locals_symbols
#define cmn_insn_canonicalize_locals_symbols src_insn_canonicalize_locals_symbols
#define cmn_iseq_fill_memtouchs src_iseq_fill_memtouchs
#define cmn_insn_add_memtouch src_insn_add_memtouch
#define cmn_insn_add_call_arg src_insn_add_call_arg
//#define cmn_insn_add_memtouch_elem src_insn_add_memtouch_elem
#define cmn_m_db_ro_entries src_m_db_ro_entries
#define CMN_M_DB_RO_NUM_ENTRIES_STR "SRC_M_DB_RO_NUM_ENTRIES"
#define cmn_insn_gen_sym_exec_reader_file src_insn_gen_sym_exec_reader_file
#define cmn_m_db_file src_m_db_file
#define cmn_insn_is_unconditional_branch_not_fcall src_insn_is_unconditional_branch_not_fcall
#define cmn_insn_is_function_return src_insn_is_function_return
#define cmn_insn_put_jump_to_nextpc src_insn_put_jump_to_nextpc
#define cmn_insn_put_jump_to_pcrel src_insn_put_jump_to_pcrel
#define cmn_strict_canonicalization_state_t src_strict_canonicalization_state_t
#define cmn_insn_get_max_num_imm_operands src_insn_get_max_num_imm_operands
#define cmn_insn_exists_in_list src_insn_exists_in_list
#define cmn_insns_equal src_insns_equal
#define cmn_pc_get_function_name_and_insn_num src_pc_get_function_name_and_insn_num
#define cmn_regset_truncate_masks_based_on_reg_sizes_in_insn src_regset_truncate_masks_based_on_reg_sizes_in_insn
#define cmn_insn_get_size_for_exreg src_insn_get_size_for_exreg
#define cmn_iseq_rename_nextpcs src_iseq_rename_nextpcs
#define cmn_insn_rename_nextpcs src_insn_rename_nextpcs
#define cmn_insn_get_tfg_from_insn_db_match src_insn_get_tfg_from_insn_db_match
#define cmn_get_tfg_from_insn_db_list_elem src_get_tfg_from_insn_db_list_elem
#define cmn_usedef_tab_init src_usedef_tab_init
#define cmn_usedef_tab_read_from_file src_usedef_tab_read_from_file
#define cmn_usedef_db_read src_usedef_db_read
#define cmn_ts_tab_read_from_file src_ts_tab_read_from_file
#define cmn_types_db_read src_types_db_read
#define usedef_tab_cmn usedef_tab_src
#define cmn_ts_tab_init src_ts_tab_init
#define ts_tab_cmn ts_tab_src
#define cmn_insn_find_ts_tab_entry src_insn_find_ts_tab_entry
#define cmn_prefix "src"
#define cmn_iseq_serialize src_iseq_serialize
#define cmn_iseq_deserialize src_iseq_deserialize
#else
#define CMN_ARCH ARCH_DST
#define CMN_MAX_NUM_OPERANDS DST_MAX_NUM_OPERANDS
//#define CMN_FALLBACK DST_FALLBACK
#define cmn_iseq_convert_pcs_to_inums dst_iseq_convert_pcs_to_inums
#define cmn_iseq_rename_abs_inums_using_map dst_iseq_rename_abs_inums_using_map
#define cmn_iseq_rename_sboxed_abs_inums_using_map dst_iseq_rename_sboxed_abs_inums_using_map
#define cmn_iseq_rename_abs_inum_tags_using_map dst_iseq_rename_abs_inum_tags_using_map
#define cmn_iseq_convert_pcrel_inums_to_abs_inums dst_iseq_convert_pcrel_inums_to_abs_inums
#define cmn_iseq_convert_abs_inums_to_pcrel_inums dst_iseq_convert_abs_inums_to_pcrel_inums
#define cmn_iseq_convert_sboxed_abs_inums_to_pcrel_inums dst_iseq_convert_sboxed_abs_inums_to_pcrel_inums
#define cmn_iseq_convert_sboxed_abs_inums_to_binpcrel_inums dst_iseq_convert_sboxed_abs_inums_to_binpcrel_inums
#define cmn_iseq_convert_abs_inum_tags_to_pcrel_inums dst_iseq_convert_abs_inum_tags_to_pcrel_inums
#define cmn_iseq_eliminate_nops dst_iseq_eliminate_nops
#define cmn_iseq_canonicalize_jump_targets dst_iseq_canonicalize_jump_targets
#define cmn_insn_put_nop dst_insn_put_nop
#define cmn_insn_is_nop dst_insn_is_nop
#define cmn_insn_copy dst_insn_copy
#define cmn_iseq_copy dst_iseq_copy
#define cmn_insn_t dst_insn_t
#define cmn_iseq_to_string dst_iseq_to_string
#define cmn_insn_is_indirect_branch dst_insn_is_indirect_branch
#define cmn_insn_get_pcrel_values dst_insn_get_pcrel_values
#define cmn_insn_set_pcrel_values dst_insn_set_pcrel_values
#define cmn_insn_get_pcrel_operands dst_insn_get_pcrel_operands
#define cmn_gen_sym_exec_db dst_gen_sym_exec_db
#define cmn_gen_sym_exec_reader_file dst_gen_sym_exec_reader_file
#define cmn_gen_sym_exec_reader_file_entry_for_insn dst_gen_sym_exec_reader_file_entry_for_insn
#define cmn_gen_insn_usedef_db dst_gen_insn_usedef_db
#define cmn_gen_insn_types_db dst_gen_insn_types_db
#define cmn_get_usedef_using_transfer_function dst_get_usedef_using_transfer_function
//#define cmn_get_type_constraints_using_transfer_function dst_get_type_constraints_using_transfer_function
#define cmn_get_type_transfers_using_transfer_function dst_get_type_transfers_using_transfer_function
#define cmn_insn_list_elem_t dst_insn_list_elem_t
#define cmn_insn_add_memtouch_variants_to_list dst_insn_memtouch_variants_add_to_list
#define cmn_insn_add_nop_insn_to_list dst_insn_add_nop_insn_to_list
#define cmn_read_insn_list_from_file dst_read_insn_list_from_file
#define cmn_insn_list_free dst_insn_list_free
#define cmn_insn_fetch_raw dst_insn_fetch_raw
#define cmn_iseq_strict_canonicalize dst_iseq_strict_canonicalize
#define cmn_get_transfer_state_str dst_get_transfer_state_str
#define cmn_insn_arg dst_insn_arg
#define cmn_insn_to_int_array dst_insn_to_int_array
#define cmn_cpp_insn_to_string dst_cpp_insn_to_string
//#define cmn_apply_transfer_fun dst_apply_transfer_fun
//#define cmn_iseq_matches_template_var dst_iseq_matches_template_var
#define cmn_get_labels_rec dst_get_labels_rec
#define cmn_get_labels dst_get_labels
#define cmn_get_loop_heads_rec dst_get_loop_heads_rec
#define cmn_get_loop_heads dst_get_loop_heads
#define cmn_get_next_pc_pred_states dst_get_next_pc_pred_states
#define cmn_get_successors dst_get_successors
#define cmn_get_tfg_from_db_iterator dst_get_tfg_from_db_iterator
#define cmn_insn_get_tfg_matching_at_iter dst_insn_get_tfg_matching_at_iter
#define cmn_insn_get_next_matching_iterator dst_insn_get_next_matching_iterator
#define cmn_get_tfg dst_get_tfg
#define cmn_get_tfg_full dst_get_tfg_full
#define cmn_insn_get_tfg dst_insn_get_tfg
#define cmn_m_db dst_m_db
#define cmn_add dst_add
#define cmn_iseq_from_string dst_iseq_from_string
#define cmn_parse_sym_exec_db dst_parse_sym_exec_db
#define cmn_sym_exec_db_filename "dst_sym_exec_db"
#define cmn_get_fresh_state_str dst_get_fresh_state_str
#define cmn_insn_is_function_call dst_insn_is_function_call
#define cmn_get_base_state dst_get_base_state
#define cmn_m_base_state dst_m_base_state
#define cmn_ulong dst_ulong
#define cmn_is_src false
#define cmn_print_usedef_mismatch dst_print_usedef_mismatch
#define cmn_insn_get_usedef dst_insn_get_usedef
#define cmn_insn_get_usedef_regs dst_insn_get_usedef_regs
#define cmn_iseq_get_usedef dst_iseq_get_usedef
#define cmn_iseq_get_usedef_regs dst_iseq_get_usedef_regs
#define cmn_insn_find_usedef_tab_entry dst_insn_find_usedef_tab_entry
#define cmn_insn_type_signature_supported dst_insn_type_signature_supported
#define cmn_iseq_canonicalize dst_iseq_canonicalize
#define cmn_insn_canonicalize dst_insn_canonicalize
#define cmn_iseq_eliminate_nops dst_iseq_eliminate_nops
#define cmn_iseq_strict_canonicalize_helper dst_iseq_strict_canonicalize_helper
#define cmn_iseq_strict_canonicalize_regs dst_iseq_strict_canonicalize_regs
#define cmn_operand_strict_canonicalize_regs dst_operand_strict_canonicalize_regs
#define cmn_operand_strict_canonicalize_imms dst_operand_strict_canonicalize_imms
#define cmn_memtouch_strict_canonicalize dst_memtouch_strict_canonicalize
#define cmn_infer_regcons_from_assembly dst_infer_regcons_from_assembly
//#define cmn_peep_preprocess_using_regmap dst_peep_preprocess_using_regmap
#define cmn_iseq_disassemble dst_iseq_disassemble
#define cmn_iseq_disassemble_with_bin_offsets dst_iseq_disassemble_with_bin_offsets
#define cmn_iseq_inv_rename dst_iseq_inv_rename
#define cmn_insn_disassemble dst_insn_disassemble
#define cmn_insn_add_to_pcrels dst_insn_add_to_pcrels
#define cmn_insn_inv_rename_registers dst_insn_inv_rename_registers
#define cmn_insn_inv_rename_memory_operands dst_insn_inv_rename_memory_operands
#define cmn_insn_inv_rename_constants dst_insn_inv_rename_constants
#define cmn_assemble dst_assemble
#define cmn_exregname_suffix dst_exregname_suffix
//#define cmn_fingerprintdb_elem_t dst_fingerprintdb_elem_t
//#define cmn_fingerprintdb_init dst_fingerprintdb_init
//#define cmn_fingerprintdb_free dst_fingerprintdb_free
//#define cmn_fingerprintdb_elem_free dst_fingerprintdb_elem_free
//#define cmn_fingerprintdb_to_string dst_fingerprintdb_to_string
//#define cmn_fingerprintdb_add_variants dst_fingerprintdb_add_variants
//#define cmn_fingerprintdb_add_from_fp dst_fingerprintdb_add_from_fp
//#define cmn_fingerprintdb_add_from_string dst_fingerprintdb_add_from_string
//#define cmn_fingerprintdb_is_empty dst_fingerprintdb_is_empty
//#define cmn_fingerprintdb_to_string dst_fingerprintdb_to_string
#define cmn_iseq_compute_fingerprint dst_iseq_compute_fingerprint
#define fscanf_harvest_output_cmn fscanf_harvest_output_dst
//#define cmn_fingerprintdb_search_for_matching_comment dst_fingerprintdb_search_for_matching_comment
#define cmn_iseq_matches_with_symbols dst_iseq_matches_with_symbols
#define cmn_insn_symbols_are_contained_in_map dst_insn_symbols_are_contained_in_map
#define map_symbols_are_contained_in_cmn_iseq map_symbols_are_contained_in_dst_iseq
#define symbol_is_contained_in_cmn_insn symbol_is_contained_in_dst_insn
//#define cmn_harvested_iseq_to_string dst_harvested_iseq_to_string
#define cmn_iseq_hash_func_after_canon dst_iseq_hash_func_after_canon
#define cmn_iseq_hash_canonicalize dst_iseq_hash_canonicalize
#define cmn_iseq_hash_func dst_iseq_hash_func
#define cmn_insn_hash_canonicalize dst_insn_hash_canonicalize
#define cmn_iseq_canonicalize_symbols dst_iseq_canonicalize_symbols
#define cmn_iseq_canonicalize_locals dst_iseq_canonicalize_locals
#define cmn_iseq_canonicalize_locals_symbols dst_iseq_canonicalize_locals_symbols
#define cmn_insn_canonicalize_locals_symbols dst_insn_canonicalize_locals_symbols
#define cmn_iseq_fill_memtouchs dst_iseq_fill_memtouchs
#define cmn_insn_add_memtouch dst_insn_add_memtouch
#define cmn_insn_add_call_arg dst_insn_add_call_arg
//#define cmn_insn_add_memtouch_elem dst_insn_add_memtouch_elem
#define cmn_m_db_ro_entries dst_m_db_ro_entries
#define CMN_M_DB_RO_NUM_ENTRIES_STR "DST_M_DB_RO_NUM_ENTRIES"
#define cmn_insn_gen_sym_exec_reader_file dst_insn_gen_sym_exec_reader_file
#define cmn_m_db_file dst_m_db_file
#define cmn_insn_is_unconditional_branch_not_fcall dst_insn_is_unconditional_branch_not_fcall
#define cmn_insn_is_function_return dst_insn_is_function_return
#define cmn_insn_put_jump_to_nextpc dst_insn_put_jump_to_nextpc
#define cmn_insn_put_jump_to_pcrel dst_insn_put_jump_to_pcrel
#define cmn_strict_canonicalization_state_t dst_strict_canonicalization_state_t
#define cmn_insn_get_max_num_imm_operands dst_insn_get_max_num_imm_operands
#define cmn_insn_exists_in_list dst_insn_exists_in_list
#define cmn_insns_equal dst_insns_equal
#define cmn_pc_get_function_name_and_insn_num dst_pc_get_function_name_and_insn_num
#define cmn_regset_truncate_masks_based_on_reg_sizes_in_insn dst_regset_truncate_masks_based_on_reg_sizes_in_insn
#define cmn_insn_get_size_for_exreg dst_insn_get_size_for_exreg
#define cmn_iseq_rename_nextpcs dst_iseq_rename_nextpcs
#define cmn_insn_rename_nextpcs dst_insn_rename_nextpcs
#define cmn_insn_get_tfg_from_insn_db_match dst_insn_get_tfg_from_insn_db_match
#define cmn_get_tfg_from_insn_db_list_elem dst_get_tfg_from_insn_db_list_elem
#define cmn_usedef_tab_init dst_usedef_tab_init
#define cmn_usedef_tab_read_from_file dst_usedef_tab_read_from_file
#define cmn_usedef_db_read dst_usedef_db_read
#define cmn_ts_tab_read_from_file dst_ts_tab_read_from_file
#define cmn_types_db_read dst_types_db_read
#define usedef_tab_cmn usedef_tab_dst
#define cmn_ts_tab_init dst_ts_tab_init
#define ts_tab_cmn ts_tab_dst
#define cmn_insn_find_ts_tab_entry dst_insn_find_ts_tab_entry
#define cmn_prefix "dst"
#define cmn_iseq_serialize dst_iseq_serialize
#define cmn_iseq_deserialize dst_iseq_deserialize
#endif
