#ifndef ETFG_REGSET_H
#define ETFG_REGSET_H

#include <stdbool.h>
#include "i386/cpu_consts.h"

#define ETFG_EXREG_GROUP_GPRS 0
#define ETFG_EXREG_GROUP_CALLEE_SAVE_REGS 1
#define ETFG_EXREG_GROUP_RETURN_REGS 2
#define ETFG_EXREG_GROUP_HIDDEN_REGS 3

#define ETFG_NUM_GPRS 32
#define ETFG_NUM_CALLEE_SAVE_REGS LLVM_NUM_CALLEE_SAVE_REGS
#define ETFG_NUM_RETURN_REGS 1
#define ETFG_NUM_HIDDEN_REGS 1

#define ETFG_NUM_EXREG_GROUPS 4

#define ETFG_NUM_INVISIBLE_REGS 0
#define ETFG_INVISIBLE_REGS_LEN(i) BYTE_LEN

#define ETFG_NUM_EXREGS(i) ( \
    (i == ETFG_EXREG_GROUP_GPRS) ? ETFG_NUM_GPRS: \
    (i == ETFG_EXREG_GROUP_CALLEE_SAVE_REGS) ? ETFG_NUM_CALLEE_SAVE_REGS: \
    (i == ETFG_EXREG_GROUP_RETURN_REGS) ? ETFG_NUM_RETURN_REGS: \
    (i == ETFG_EXREG_GROUP_HIDDEN_REGS) ? ETFG_NUM_HIDDEN_REGS: \
    0) /* should be in decreasing order */
#define ETFG_EXREG_LEN(i) ( \
    (i == ETFG_EXREG_GROUP_GPRS) ? DWORD_LEN: \
    (i == ETFG_EXREG_GROUP_CALLEE_SAVE_REGS) ? DWORD_LEN: \
    (i == ETFG_EXREG_GROUP_RETURN_REGS) ? DWORD_LEN: \
    (i == ETFG_EXREG_GROUP_HIDDEN_REGS) ? DWORD_LEN: \
    0)

#define ETFG_EXREG_MASK(i) ( \
    (i == ETFG_EXREG_GROUP_GPRS) ? MAKE_MASK(DWORD_LEN): \
    (i == ETFG_EXREG_GROUP_CALLEE_SAVE_REGS) ? MAKE_MASK(DWORD_LEN): \
    (i == ETFG_EXREG_GROUP_RETURN_REGS) ? MAKE_MASK(DWORD_LEN): \
    (i == ETFG_EXREG_GROUP_HIDDEN_REGS) ? MAKE_MASK(DWORD_LEN): \
    0 )

/*#define ETFG_ENV_EXOFF(i, j) ( \
    (i == ETFG_EXREG_GROUP_GPRS) ? (j * 4) : 0)*/
#define ETFG_ENV_EXOFF(i, j) ( \
    (i == ETFG_EXREG_GROUP_GPRS) ? (j * (ETFG_MAX_REG_SIZE/BYTE_LEN)): \
    (i == ETFG_EXREG_GROUP_CALLEE_SAVE_REGS) ? (ETFG_NUM_GPRS * (ETFG_MAX_REG_SIZE/BYTE_LEN) + j * (ETFG_MAX_REG_SIZE/BYTE_LEN)): \
    (i == ETFG_EXREG_GROUP_RETURN_REGS) ? (ETFG_NUM_GPRS * (ETFG_MAX_REG_SIZE/BYTE_LEN) + ETFG_NUM_CALLEE_SAVE_REGS * (ETFG_MAX_REG_SIZE/BYTE_LEN) + j * (ETFG_MAX_REG_SIZE/BYTE_LEN)): \
    (i == ETFG_EXREG_GROUP_HIDDEN_REGS) ? (ETFG_NUM_GPRS * (ETFG_MAX_REG_SIZE/BYTE_LEN) + ETFG_NUM_CALLEE_SAVE_REGS * (ETFG_MAX_REG_SIZE/BYTE_LEN) + ETFG_NUM_RETURN_REGS * (ETFG_MAX_REG_SIZE/BYTE_LEN) + j * (ETFG_MAX_REG_SIZE/BYTE_LEN)): \
    ({NOT_REACHED(); -1;}))

#define ETFG_MAX_REG_SIZE DWORD_LEN
#endif
