#pragma once

#include "i386/regs.h"

#define X64_NUM_EXREG_GROUPS I386_NUM_EXREG_GROUPS
#define X64_NUM_GPRS 16
#define X64_NUM_XMMREGS 16
#define X64_EXREG_GROUP_GPRS I386_EXREG_GROUP_GPRS
#define X64_EXREG_GROUP_FP_DATA_REGS I386_EXREG_GROUP_FP_DATA_REGS
#define X64_EXREG_GROUP_ST_TOP I386_EXREG_GROUP_ST_TOP

#define X64_NUM_EXREGS(i) ( \
    (i == I386_EXREG_GROUP_GPRS) ? X64_NUM_GPRS: \
    (i == I386_EXREG_GROUP_XMM) ? X64_NUM_XMMREGS: I386_NUM_EXREGS(i) \
)

#define X64_EXREG_LEN(i) ( \
    (i == I386_EXREG_GROUP_GPRS) ? QWORD_LEN: \
    (i == I386_EXREG_GROUP_EFLAGS_OTHER) ? QWORD_LEN: I386_EXREG_LEN(i) \
)

#define X64_EXREG_MASK(i) (MAKE_MASK(X64_EXREG_LEN(i)))

#define X64_ENV_EXOFF I386_ENV_EXOFF
