#include "config-host.h"

#if ARCH_SRC == ARCH_ETFG

#define src_insn_t             etfg_insn_t
#define SRC_NAME               "etfg"
#define SRC_NUM_EXREG_GROUPS   ETFG_NUM_EXREG_GROUPS
#define SRC_NUM_EXREGS         ETFG_NUM_EXREGS
#define SRC_EXREG_GROUP_GPRS   ETFG_EXREG_GROUP_GPRS
#define SRC_EXREG_LEN          ETFG_EXREG_LEN
#define SRC_ENV_EXOFF          ETFG_ENV_EXOFF
#define SRC_MAX_NUM_OPERANDS   ETFG_MAX_NUM_OPERANDS
#define src_operand_strict_canonicalize_regs etfg_operand_strict_canonicalize_regs
#define src_operand_strict_canonicalize_imms etfg_operand_strict_canonicalize_imms
#define src_exregname_suffix   etfg_exregname_suffix
#define src_iseq_to_string     etfg_iseq_to_string
#define src_iseq_contents_to_string etfg_iseq_to_string
#define src_insn_to_string     etfg_insn_to_string
#define SRC_STACK_REGNUM       0
#define src_insn_to_int_array  etfg_insn_to_int_array
#define src_insn_rename_addresses_to_symbols etfg_insn_rename_addresses_to_symbols
#define src_insn_copy_symbols  etfg_insn_copy_symbols
#define src_insns_equal        etfg_insns_equal
#define src_insn_get_symbols   etfg_insn_get_symbols
#define src_iseq_matches_template etfg_iseq_matches_template
//#define src_iseq_matches_template_var etfg_iseq_matches_template_var
#define src_insn_copy          etfg_insn_copy
#define src_insn_hash_func etfg_insn_hash_func
#define src_insn_fetch_raw etfg_insn_fetch_raw
#define src_insn_merits_optimization etfg_insn_merits_optimization
#define src_insn_is_nop etfg_insn_is_nop
#define src_insn_canonicalize_locals_symbols etfg_insn_canonicalize_locals_symbols
#define src_insn_fetch_preprocess etfg_insn_fetch_preprocess
#define src_iseq_supports_execution_test etfg_iseq_supports_execution_test
#define src_insn_branch_targets etfg_insn_branch_targets
#define src_insn_fcall_target etfg_insn_fcall_target
#define src_insn_put_jump_to_pcrel etfg_insn_put_jump_to_pcrel
#define src_insn_put_jump_to_abs_inum etfg_insn_put_jump_to_abs_inum
#define src_insn_get_pcrel_values etfg_insn_get_pcrel_values
#define src_insn_less            etfg_insn_less
#define src_insn_terminates_bbl    etfg_insn_terminates_bbl
#define src_insn_is_indirect_branch etfg_insn_is_indirect_branch
#define src_insn_is_direct_function_call  etfg_insn_is_direct_function_call
#define src_insn_is_indirect_function_call  etfg_insn_is_indirect_function_call
#define src_insn_is_unconditional_direct_branch_not_fcall etfg_insn_is_unconditional_direct_branch_not_fcall
#define src_insn_is_unconditional_branch etfg_insn_is_unconditional_branch
#define src_iseq_mark_used_vconstants etfg_iseq_mark_used_vconstants
#define src_insn_get_min_max_vconst_masks etfg_insn_get_min_max_vconst_masks
#define src_insn_get_min_max_mem_vconst_masks etfg_insn_get_min_max_mem_vconst_masks
#define src_insn_is_unconditional_branch_not_fcall etfg_insn_is_unconditional_branch_not_fcall
#define src_insn_is_direct_function_call  etfg_insn_is_direct_function_call
#define src_insn_is_indirect_function_call  etfg_insn_is_indirect_function_call
#define src_insn_is_function_call  etfg_insn_is_function_call
#define src_insn_is_function_return etfg_insn_is_function_return
#define src_insn_is_conditional_indirect_branch etfg_insn_is_conditional_indirect_branch
#define src_insn_is_indirect_branch_not_fcall etfg_insn_is_indirect_branch_not_fcall
#define src_insn_hash_canonicalize etfg_insn_hash_canonicalize
#define src_insn_supports_boolean_test  etfg_insn_supports_boolean_test
#define src_insn_supports_execution_test  etfg_insn_supports_execution_test
#define src_insn_symbols_are_contained_in_map etfg_insn_symbols_are_contained_in_map
#define src_insn_put_jump_to_nextpc etfg_insn_put_jump_to_nextpc
#define src_insn_get_pcrel_values   etfg_insn_get_pcrel_values
#define src_insn_set_pcrel_values   etfg_insn_set_pcrel_values
#define src_insn_get_pcrel_operands etfg_insn_get_pcrel_operands
#define src_insn_inv_rename_registers        etfg_insn_inv_rename_registers
#define src_insn_inv_rename_memory_operands  etfg_insn_inv_rename_memory_operands
#define src_insn_inv_rename_constants        etfg_insn_inv_rename_constants
#define symbol_is_contained_in_src_insn      symbol_is_contained_in_etfg_insn
#define src_insn_add_to_pcrels      etfg_insn_add_to_pcrels
#define src_insn_canonicalize      etfg_insn_canonicalize
#define src_insn_is_conditional_direct_branch etfg_insn_is_conditional_direct_branch
#define src_init                 etfg_init
#define src_insn_disassemble     etfg_insn_disassemble
#define src_infer_regcons_from_assembly etfg_infer_regcons_from_assembly
#define src_assemble etfg_assemble
#define src_insn_get_constant_operand etfg_insn_get_constant_operand
#define SRC_NOP_INSN_SIZE          1
#define src_insn_put_nop           etfg_insn_put_nop
#define src_insn_put_move_imm_to_mem etfg_insn_put_move_imm_to_mem
#define src_insn_type_signature_supported etfg_insn_type_signature_supported
#define src_insn_put_nop_as        etfg_insn_put_nop_as
#define src_insn_put_linux_exit_syscall_as etfg_insn_put_linux_exit_syscall_as
#define src_iseq_rename_regs_and_imms etfg_iseq_rename_regs_and_imms
#define src_regset_live_at_jumptable etfg_regset_live_at_jumptable
#define src_strict_canonicalization_state_t etfg_strict_canonicalization_state_t
#define src_strict_canonicalization_state_init etfg_strict_canonicalization_state_init
#define src_strict_canonicalization_state_free etfg_strict_canonicalization_state_free
#define src_insn_get_max_num_imm_operands etfg_insn_get_max_num_imm_operands
#define src_pc_get_function_name_and_insn_num etfg_pc_get_function_name_and_insn_num
//#define src_insn_rename_nextpcs              etfg_insn_rename_nextpcs
#define src_insn_put_function_return         etfg_insn_put_function_return
#define src_insn_put_invalid                 etfg_insn_put_invalid
#define src_insn_put_ret_insn                etfg_insn_put_ret_insn
#define src_insn_rename_constants            etfg_insn_rename_constants
//#define src_iseq_hash_func_after_canon  etfg_iseq_hash_func_after_canon
#define src_iseq_stores_eq_comparison_in_reg etfg_iseq_stores_eq_comparison_in_reg
#define src_iseq_stores_ult_comparison_in_reg etfg_iseq_stores_ult_comparison_in_reg
#define src_iseq_stores_slt_comparison_in_reg etfg_iseq_stores_slt_comparison_in_reg
#define src_iseq_stores_ugt_comparison_in_reg etfg_iseq_stores_ugt_comparison_in_reg
#define src_iseq_stores_sgt_comparison_in_reg etfg_iseq_stores_sgt_comparison_in_reg
#define src_iseq_involves_cbranch etfg_iseq_involves_cbranch
#define src_iseq_is_function_tailcall_opt_candidate etfg_iseq_is_function_tailcall_opt_candidate
#define src_iseq_with_relocs_to_string     etfg_iseq_with_relocs_to_string
#define src_insn_convert_pcrels_and_symbols_to_reloc_strings   etfg_insn_convert_pcrels_and_symbols_to_reloc_strings
#define src_identity_regmap        etfg_identity_regmap
#define src_iseq_rename            etfg_iseq_rename
#define src_insn_inv_rename_registers        etfg_insn_inv_rename_registers
#define src_insn_inv_rename_memory_operands  etfg_insn_inv_rename_memory_operands


#elif ARCH_SRC == ARCH_PPC
#define SRC_MAX_NUM_OPERANDS     PPC_MAX_NUM_OPERANDS
#define SRC_EXREG_GROUP_GPRS     PPC_EXREG_GROUP_GPRS
#define SRC_NAME                 "ppc"
#define src_insn_t           ppc_insn_t
#define src_memset_t             ppc_memset_t
//#define src_regmap_t             ppc_regmap_t
#define src_insn_disassemble     ppc_insn_disassemble
#define src_insn_copy            ppc_insn_copy
#define src_insn_less            ppc_insn_less
#define src_insn_hash_func       ppc_insn_hash_func
//#define src_insn_init            ppc_insn_init
#define src_insn_to_string       ppc_insn_to_string
//#define src_insn_get_usedef_regs ppc_insn_get_usedef_regs
//#define src_insn_get_usedef_vregs ppc_insn_get_usedef_vregs
//#define src_iseq_get_usedef_regs ppc_iseq_get_usedef_regs
#define src_iseq_matches_template ppc_iseq_matches_template
//#define src_iseq_matches_template_var ppc_iseq_matches_template_var
#define src_iseq_to_string         ppc_iseq_to_string
#define src_iseq_contents_to_string ppc_iseq_contents_to_string
//#define src_regmap_init            ppc_regmap_init
#define src_get_regnum_from_vname  ppc_get_regnum_from_vname
//#define src_regset_from_string     ppc_regset_from_string
//#define src_regset_to_string       ppc_regset_to_string
//#define src_regname                ppc_regname
#define src_inv_regmap_agrees_with_nomatch_pairs ppc_inv_regmap_agrees_with_nomatch_pairs
//#define src_iseq_canonicalize      ppc_iseq_canonicalize
#define src_insn_canonicalize      ppc_insn_canonicalize
#define src_rdefs_t                ppc_rdefs_t
#define src_rdefs_contains_crf_logical_op ppc_rdefs_contains_crf_logical_op
#define src_live_ranges_t          ppc_live_ranges_t
#define src_insn_hash_canonicalize ppc_insn_hash_canonicalize
//#define src_iseq_strict_canonicalize ppc_iseq_strict_canonicalize
#define src_insn_from_string       ppc_insn_from_string
//#define src_iseq_from_string       ppc_iseq_from_string
//#define get_src_usedef             get_ppc_usedef
//#define snprint_insn_src           snprint_insn_ppc
//#define src_regmap_to_string       ppc_regmap_to_string
#define src_live_range             ppc_live_range
//#define SRC_NUM_REGS               PPC_NUM_REGS
#define SRC_NUM_EXREG_GROUPS       PPC_NUM_EXREG_GROUPS
#define SRC_NUM_EXREGS             PPC_NUM_EXREGS
#define SRC_EXREG_LEN              PPC_EXREG_LEN
#define SRC_NUM_INVISIBLE_REGS     PPC_NUM_INVISIBLE_REGS
#define SRC_INVISIBLE_REGS_LEN     PPC_INVISIBLE_REGS_LEN
#define SRC_ENV_EXOFF              PPC_ENV_EXOFF
#define src_identity_regmap        ppc_identity_regmap
#define src_volatile_regs          ppc_volatile_regs
#define src_iseq_get_num_canon_constants ppc_iseq_get_num_canon_constants
//#define src_iseq_get_num_sh_canon_constants ppc_iseq_get_num_sh_canon_constants
//#define src_iseq_get_usedef        ppc_iseq_get_usedef
//#define src_insn_get_usedef        ppc_insn_get_usedef
#define src_insn_terminates_bbl    ppc_insn_terminates_bbl
#define src_insn_is_indirect_branch ppc_insn_is_indirect_branch
#define src_insn_is_indirect_branch_not_fcall ppc_insn_is_indirect_branch_not_fcall
//#define CPUState                   CPUPPCState
#define src_insn_fetch_raw         ppc_insn_fetch_raw
//#define src_iseq_from_insns        ppc_iseq_from_insns
#define src_insn_get_bincode       ppc_insn_get_bincode
#define SRC_NUM_GPRS               PPC_NUM_GPRS
#define src_insn_is_function_call  ppc_insn_is_function_call
#define src_insn_is_function_return ppc_insn_is_function_return
#define src_insn_is_branch_not_fcall ppc_insn_is_branch_not_fcall
#define src_insn_is_unconditional_direct_branch ppc_insn_is_unconditional_direct_branch
#define src_insn_is_unconditional_direct_branch_not_fcall ppc_insn_is_unconditional_direct_branch_not_fcall
#define src_insn_is_conditional_direct_branch ppc_insn_is_conditional_direct_branch
#define src_insn_is_conditional_indirect_branch ppc_insn_is_conditional_indirect_branch
#define src_insn_is_unconditional_branch  ppc_insn_is_unconditional_branch
#define src_insn_is_unconditional_branch_not_fcall  ppc_insn_is_unconditional_branch_not_fcall
#define src_insn_is_direct_function_call  ppc_insn_is_direct_function_call
#define src_insn_is_indirect_function_call  ppc_insn_is_indirect_function_call
#define src_insn_is_nop            ppc_insn_is_nop
#define src_insn_assemble          ppc_insn_assemble
#define src_insn_branch_targets     ppc_insn_branch_targets
#define src_insn_fcall_target     ppc_insn_fcall_target
#define src_insn_branch_target_var ppc_insn_branch_target_var
//#define SRC_MAX_ILEN               PPC_MAX_ILEN
//#define SRC_ISEQ_MAX_EXITS         PPC_ISEQ_MAX_EXITS
#define src_gen_mem_modes          generic_gen_mem_modes
#define src_gen_jcc_conds          generic_gen_jcc_conds
#define src_insn_get_constant_operand ppc_insn_get_constant_operand
#define src_iseq_assign_vregs_to_cregs  ppc_iseq_assign_vregs_to_cregs
#define src_setup_executable_code  ppc_setup_executable_code
#define SRC_INSN_ARGSLEN           PPC_INSN_ARGSLEN
#define SRC_REGSET_ARGSLEN         PPC_REGSET_ARGSLEN
#define src_iseq_compute_execution_cost      ppc_iseq_compute_cost
#define src_insn_to_int_array      ppc_insn_to_int_array
#define src_insn_add_to_pcrels      ppc_insn_add_to_pcrels
//#define src_insn_is_not_harvestable ppc_insn_is_not_harvestable
#define src_iseq_can_be_optimized  ppc_iseq_can_be_optimized
#define src_insn_put_jump_to_nextpc ppc_insn_put_jump_to_nextpc
#define src_insn_put_jump_to_abs_inum ppc_insn_put_jump_to_abs_inum
#define src_insn_set_pcrel_values   ppc_insn_set_pcrel_values
#define src_insn_get_pcrel_values   ppc_insn_get_pcrel_values
#define src_setup_on_startup       ppc_setup_on_startup
#define src_iseq_rename_regs_and_imms ppc_iseq_rename_regs_and_imms
#define src_insn_put_nop_as        ppc_insn_put_nop_as
#define src_insn_put_linux_exit_syscall_as ppc_insn_put_linux_exit_syscall_as
//#define src_regmap_count_gprs      ppc_regmap_count_gprs
//#define src_regmap_change_val      ppc_regmap_change_val
#define SRC_NOP_INSN_SIZE          4
#define src_init                 ppc_init
#define src_insn_rename_constants  ppc_insn_rename_constants
#define SRC_STACK_REGNUM           1
#define src_infer_regcons_from_assembly ppc_infer_regcons_from_assembly
#define src_iseq_rename            ppc_iseq_rename
#define src_insn_supports_boolean_test  ppc_insn_supports_boolean_test
#define src_insn_supports_execution_test  ppc_insn_supports_execution_test
#define src_iseq_supports_execution_test  ppc_iseq_supports_execution_test
#define src_insn_merits_optimization  ppc_insn_merits_optimization
#define src_iseq_mark_used_vconstants ppc_iseq_mark_used_vconstants
#define src_iseq_compute_num_nextpcs  ppc_iseq_compute_num_nextpcs
//#define src_insn_collect_typestate_constraints ppc_insn_collect_typestate_constraints
#define src_insn_get_min_max_vconst_masks ppc_insn_get_min_max_vconst_masks
#define src_insn_get_min_max_mem_vconst_masks ppc_insn_get_min_max_mem_vconst_masks
#define src_insn_type_signature_supported ppc_insn_type_signature_supported
#define src_operand_strict_canonicalize_regs ppc_operand_strict_canonicalize_regs
#define src_operand_strict_canonicalize_imms ppc_operand_strict_canonicalize_imms
#define src_memtouch_strict_canonicalize     ppc_memtouch_strict_canonicalize
#define src_insn_get_pcrel_operands           ppc_insn_get_pcrel_operands
#define src_insn_inv_rename_registers        ppc_insn_inv_rename_registers
#define src_insn_inv_rename_memory_operands  ppc_insn_inv_rename_memory_operands
#define src_insn_inv_rename_constants        ppc_insn_inv_rename_constants
#define src_assemble                         ppc_assemble
#define src_exregname_suffix                 ppc_exregname_suffix
#define src_iseqs_equal_mod_imms             ppc_iseqs_equal_mod_imms
#define src_insn_canonicalize_locals_symbols ppc_insn_canonicalize_locals_symbols
#define src_insn_symbols_are_contained_in_map ppc_insn_symbols_are_contained_in_map
#define symbol_is_contained_in_src_insn      symbol_is_contained_in_ppc_insn
#define src_insn_rename_rodata_ptrs          ppc_insn_rename_rodata_ptrs
#define src_insn_rename_addresses_to_symbols ppc_insn_rename_addresses_to_symbols
//#define src_iseq_hash_func         ppc_iseq_hash_func
#define src_insn_put_nop           ppc_insn_put_nop
#define src_insn_put_move_imm_to_mem ppc_insn_put_move_imm_to_mem
#define src_insns_equal                  ppc_insns_equal
#define src_insn_copy_symbols       ppc_insn_copy_symbols
//#define src_insn_annotate_local     ppc_insn_annotate_local
#define src_insn_get_symbols        ppc_insn_get_symbols
#define src_insn_fetch_preprocess   ppc_insn_fetch_preprocess
#define src_insn_gen_sym_exec_reader_file ppc_insn_gen_sym_exec_reader_file
#define src_regset_live_at_jumptable ppc_regset_live_at_jumptable
#define src_strict_canonicalization_state_t ppc_strict_canonicalization_state_t
#define src_strict_canonicalization_state_init ppc_strict_canonicalization_state_init
#define src_strict_canonicalization_state_free ppc_strict_canonicalization_state_free
#define src_insn_get_max_num_imm_operands ppc_insn_get_max_num_imm_operands
#define src_pc_get_function_name_and_insn_num ppc_pc_get_function_name_and_insn_num
//#define src_insn_rename_nextpcs              ppc_insn_rename_nextpcs
#define src_insn_put_function_return         ppc_insn_put_function_return
#define src_insn_put_invalid                 ppc_insn_put_invalid
#define src_insn_put_ret_insn                ppc_insn_put_ret_insn
#define src_insn_rename_constants            ppc_insn_rename_constants
//#define src_iseq_hash_func_after_canon  ppc_iseq_hash_func_after_canon
#define src_iseq_is_function_tailcall_opt_candidate ppc_iseq_is_function_tailcall_opt_candidate
#define src_iseq_with_relocs_to_string     ppc_iseq_with_relocs_to_string
#define src_insn_convert_pcrels_and_symbols_to_reloc_strings   ppc_insn_convert_pcrels_and_symbols_to_reloc_strings

#elif ARCH_SRC == ARCH_I386
#define SRC_MAX_NUM_OPERANDS       I386_MAX_NUM_OPERANDS
#define SRC_EXREG_GROUP_GPRS       I386_EXREG_GROUP_GPRS
#define SRC_NAME                   "i386"
#define src_insn_t             i386_insn_t
#define src_memset_t               i386_memset_t
#define src_insn_disassemble       i386_insn_disassemble
#define src_insn_copy              i386_insn_copy
#define src_insn_less              i386_insn_less
#define src_insn_hash_func         i386_insn_hash_func
//#define src_insn_init              i386_insn_init
#define src_insn_to_string         i386_insn_to_string
#define src_iseq_matches_template  i386_iseq_matches_template
#define src_iseq_to_string         i386_iseq_to_string
#define src_iseq_contents_to_string i386_iseq_to_string
#define src_get_regnum_from_vname  i386_get_regnum_from_vname
#define src_inv_regmap_agrees_with_nomatch_pairs i386_inv_regmap_agrees_with_nomatch_pairs
#define src_insn_canonicalize      i386_insn_canonicalize
#define src_rdefs_t                i386_rdefs_t
#define src_rdefs_contains_crf_logical_op i386_rdefs_contains_crf_logical_op
#define src_live_ranges_t          i386_live_ranges_t
#define src_insn_hash_canonicalize i386_insn_hash_canonicalize
#define src_insn_from_string       i386_insn_from_string
#define get_src_usedef             get_i386_usedef
#define src_live_range             i386_live_range
#define SRC_NUM_EXREG_GROUPS       I386_NUM_EXREG_GROUPS
#define SRC_NUM_EXREGS             I386_NUM_EXREGS
#define SRC_EXREG_LEN              I386_EXREG_LEN
#define SRC_NUM_INVISIBLE_REGS     I386_NUM_INVISIBLE_REGS
#define SRC_INVISIBLE_REGS_LEN     I386_INVISIBLE_REGS_LEN
#define SRC_ENV_EXOFF              I386_ENV_EXOFF
#define src_identity_regmap        i386_identity_regmap
#define src_volatile_regs          i386_volatile_regs
#define src_iseq_get_num_canon_constants i386_iseq_get_num_canon_constants
#define src_iseq_get_num_sh_canon_constants i386_iseq_get_num_sh_canon_constants
#define src_insn_terminates_bbl    i386_insn_terminates_bbl
#define src_insn_fetch_raw         i386_insn_fetch_raw
#define src_insn_get_bincode       i386_insn_get_bincode
#define SRC_NUM_GPRS               I386_NUM_GPRS
#define src_insn_is_function_return i386_insn_is_function_return
#define src_insn_is_unconditional_branch i386_insn_is_unconditional_branch
#define src_insn_is_unconditional_direct_branch i386_insn_is_unconditional_direct_branch
#define src_insn_is_branch_not_fcall i386_insn_is_branch_not_fcall
#define src_insn_is_unconditional_branch_not_fcall i386_insn_is_unconditional_branch_not_fcall
#define src_insn_is_unconditional_direct_branch_not_fcall i386_insn_is_unconditional_direct_branch_not_fcall
#define src_insn_is_conditional_direct_branch i386_insn_is_conditional_direct_branch
#define src_insn_is_indirect_branch i386_insn_is_indirect_branch
#define src_insn_is_indirect_branch_not_fcall i386_insn_is_indirect_branch_not_fcall
#define src_insn_is_conditional_indirect_branch i386_insn_is_conditional_indirect_branch
#define src_insn_is_direct_function_call  i386_insn_is_direct_function_call
#define src_insn_is_indirect_function_call  i386_insn_is_indirect_function_call
#define src_insn_branch_targets    i386_insn_branch_targets
#define src_insn_fcall_target     i386_insn_fcall_target
#define src_insn_branch_target_var i386_insn_branch_target_var
#define src_gen_mem_modes          i386_gen_mem_modes
#define src_gen_jcc_conds          i386_gen_jcc_conds
#define src_insn_get_constant_operand i386_insn_get_constant_operand
#define src_insn_is_nop            i386_insn_is_nop
#define src_insn_assemble          i386_insn_assemble
#define src_insn_update_stack_pointers i386_insn_update_stack_pointers
#define src_insn_passes_stack_pointer i386_insn_passes_stack_pointer
#define src_insn_uses_stack_offset i386_insn_uses_stack_offset
#define src_insn_replace_stack_instruction i386_insn_replace_stack_instruction
#define src_insn_comparison_uses_induction_regs i386_insn_comparison_uses_induction_regs
#define src_iseq_can_be_optimized  i386_iseq_can_be_optimized
#define src_insn_invert_cmp_operator i386_insn_invert_cmp_operator
#define src_setup_executable_code  i386_setup_executable_code
#define src_iseq_assign_vregs_to_cregs  i386_iseq_assign_vregs_to_cregs
#define src_iseq_assign_vregs_to_cregs_using_transmap  i386_iseq_assign_vregs_to_cregs_using_transmap
#define SRC_INSN_ARGSLEN           I386_INSN_ARGSLEN
#define SRC_REGSET_ARGSLEN         I386_REGSET_ARGSLEN
#define src_iseq_compute_execution_cost i386_iseq_compute_execution_cost
#define src_insn_to_int_array      i386_insn_to_int_array
#define src_insn_add_to_pcrels      i386_insn_add_to_pcrels
#define src_insn_put_jump_to_pcrel i386_insn_put_jump_to_pcrel
#define src_insn_put_jump_to_abs_inum i386_insn_put_jump_to_abs_inum
#define src_insn_put_jump_to_nextpc i386_insn_put_jump_to_nextpc
#define src_insn_put_invalid       i386_insn_put_invalid
#define src_insn_put_jump_to_nextpc i386_insn_put_jump_to_nextpc
#define src_insn_set_nextpc        i386_insn_set_nextpc
#define src_insn_get_pcrel_values   i386_insn_get_pcrel_values
#define src_insn_set_pcrel_values   i386_insn_set_pcrel_values
#define src_setup_on_startup       i386_setup_on_startup
#define src_insn_put_linux_exit_syscall_as i386_insn_put_linux_exit_syscall_as
#define src_insn_put_nop_as        i386_insn_put_nop_as
#define src_iseq_rename_regs_and_imms i386_iseq_rename_regs_and_imms
#define src_insn_is_function_call  i386_insn_is_function_call
#define SRC_NOP_INSN_SIZE          1
#define src_init                   i386_init
#define src_insn_rename_constants  i386_insn_rename_constants
#define SRC_STACK_REGNUM           4
#define src_infer_regcons_from_assembly i386_infer_regcons_from_assembly
#define src_iseq_rename            i386_iseq_rename
#define src_iseq_execution_test_implemented i386_iseq_execution_test_implemented
#define src_insn_supports_boolean_test  i386_insn_supports_boolean_test
#define src_insn_supports_execution_test  i386_insn_supports_execution_test
#define src_iseq_supports_execution_test  i386_iseq_supports_execution_test
#define src_insn_merits_optimization  i386_insn_merits_optimization
#define src_iseq_mark_used_vconstants i386_iseq_mark_used_vconstants
#define src_iseq_compute_num_nextpcs  i386_iseq_compute_num_nextpcs
#define src_insn_get_min_max_vconst_masks i386_insn_get_min_max_vconst_masks
#define src_insn_get_min_max_mem_vconst_masks i386_insn_get_min_max_mem_vconst_masks
#define src_insn_type_signature_supported i386_insn_type_signature_supported
#define src_operand_strict_canonicalize_regs i386_operand_strict_canonicalize_regs
#define src_operand_strict_canonicalize_imms i386_operand_strict_canonicalize_imms
#define src_memtouch_strict_canonicalize     i386_memtouch_strict_canonicalize
#define src_insn_get_pcrel_operands       i386_insn_get_pcrel_operands
#define src_insn_inv_rename_registers        i386_insn_inv_rename_registers
#define src_insn_inv_rename_memory_operands  i386_insn_inv_rename_memory_operands
#define src_insn_inv_rename_constants        i386_insn_inv_rename_constants
#define src_assemble                         x86_assemble
#define src_exregname_suffix                 i386_exregname_suffix
#define src_iseqs_equal_mod_imms             i386_iseqs_equal_mod_imms
#define src_insn_canonicalize_locals_symbols i386_insn_canonicalize_locals_symbols
#define src_insn_symbols_are_contained_in_map i386_insn_symbols_are_contained_in_map
#define symbol_is_contained_in_src_insn      symbol_is_contained_in_i386_insn
#define src_insn_rename_rodata_ptrs          i386_insn_rename_rodata_ptrs
#define src_insn_rename_addresses_to_symbols i386_insn_rename_addresses_to_symbols
#define src_insn_put_nop           i386_insn_put_nop
#define src_insn_put_move_imm_to_mem i386_insn_put_movl_imm_to_mem
#define src_insns_equal                  i386_insns_equal
#define src_insn_copy_symbols       i386_insn_copy_symbols
#define src_insn_get_symbols        i386_insn_get_symbols
#define src_insn_fetch_preprocess   i386_insn_fetch_preprocess
#define src_insn_gen_sym_exec_reader_file i386_insn_gen_sym_exec_reader_file
#define src_regset_live_at_jumptable i386_regset_live_at_jumptable
#define src_strict_canonicalization_state_t i386_strict_canonicalization_state_t
#define src_strict_canonicalization_state_init i386_strict_canonicalization_state_init
#define src_strict_canonicalization_state_free i386_strict_canonicalization_state_free
#define src_insn_get_max_num_imm_operands i386_insn_get_max_num_imm_operands
#define src_pc_get_function_name_and_insn_num i386_pc_get_function_name_and_insn_num
#define src_insn_put_function_return         i386_insn_put_function_return
#define src_insn_put_invalid                 i386_insn_put_invalid
#define src_insn_put_ret_insn                i386_insn_put_ret_insn
#define src_insn_rename_constants            i386_insn_rename_constants
#define src_iseq_is_function_tailcall_opt_candidate i386_iseq_is_function_tailcall_opt_candidate
#define src_iseq_with_relocs_to_string     i386_iseq_with_relocs_to_string
#define src_insn_convert_pcrels_and_symbols_to_reloc_strings   i386_insn_convert_pcrels_and_symbols_to_reloc_strings

#elif ARCH_SRC == ARCH_X64

#define src_insn_t             x64_insn_t
#define SRC_NAME               "x64"
#define SRC_NUM_EXREG_GROUPS   X64_NUM_EXREG_GROUPS
#define SRC_NUM_EXREGS         X64_NUM_EXREGS
#define SRC_EXREG_GROUP_GPRS   X64_EXREG_GROUP_GPRS
#define SRC_EXREG_LEN          X64_EXREG_LEN
#define SRC_ENV_EXOFF          X64_ENV_EXOFF
#define SRC_MAX_NUM_OPERANDS   X64_MAX_NUM_OPERANDS
#define src_operand_strict_canonicalize_regs x64_operand_strict_canonicalize_regs
#define src_operand_strict_canonicalize_imms x64_operand_strict_canonicalize_imms
#define src_exregname_suffix   x64_exregname_suffix
#define src_iseq_to_string     x64_iseq_to_string
#define src_iseq_contents_to_string x64_iseq_to_string
#define src_insn_to_string     x64_insn_to_string
#define SRC_STACK_REGNUM       0
#define src_insn_to_int_array  x64_insn_to_int_array
#define src_insn_rename_addresses_to_symbols x64_insn_rename_addresses_to_symbols
#define src_insn_copy_symbols  x64_insn_copy_symbols
#define src_insns_equal        x64_insns_equal
#define src_insn_get_symbols   x64_insn_get_symbols
#define src_iseq_matches_template x64_iseq_matches_template
#define src_insn_copy          x64_insn_copy
#define src_insn_hash_func x64_insn_hash_func
#define src_insn_fetch_raw x64_insn_fetch_raw
#define src_insn_merits_optimization x64_insn_merits_optimization
#define src_insn_is_nop x64_insn_is_nop
#define src_insn_canonicalize_locals_symbols x64_insn_canonicalize_locals_symbols
#define src_insn_fetch_preprocess x64_insn_fetch_preprocess
#define src_iseq_supports_execution_test x64_iseq_supports_execution_test
#define src_insn_branch_targets x64_insn_branch_targets
#define src_insn_fcall_target x64_insn_fcall_target
#define src_insn_put_jump_to_pcrel x64_insn_put_jump_to_pcrel
#define src_insn_put_jump_to_abs_inum x64_insn_put_jump_to_abs_inum
#define src_insn_get_pcrel_values x64_insn_get_pcrel_values
#define src_insn_less            x64_insn_less
#define src_insn_terminates_bbl    x64_insn_terminates_bbl
#define src_insn_is_indirect_branch x64_insn_is_indirect_branch
#define src_insn_is_direct_function_call  x64_insn_is_direct_function_call
#define src_insn_is_indirect_function_call  x64_insn_is_indirect_function_call
#define src_insn_is_unconditional_direct_branch_not_fcall x64_insn_is_unconditional_direct_branch_not_fcall
#define src_insn_is_unconditional_branch x64_insn_is_unconditional_branch
#define src_iseq_mark_used_vconstants x64_iseq_mark_used_vconstants
#define src_insn_get_min_max_vconst_masks x64_insn_get_min_max_vconst_masks
#define src_insn_get_min_max_mem_vconst_masks x64_insn_get_min_max_mem_vconst_masks
#define src_insn_is_unconditional_branch_not_fcall x64_insn_is_unconditional_branch_not_fcall
#define src_insn_is_direct_function_call  x64_insn_is_direct_function_call
#define src_insn_is_indirect_function_call  x64_insn_is_indirect_function_call
#define src_insn_is_function_call  x64_insn_is_function_call
#define src_insn_is_function_return x64_insn_is_function_return
#define src_insn_is_conditional_indirect_branch x64_insn_is_conditional_indirect_branch
#define src_insn_is_indirect_branch_not_fcall x64_insn_is_indirect_branch_not_fcall
#define src_insn_hash_canonicalize x64_insn_hash_canonicalize
#define src_insn_supports_boolean_test  x64_insn_supports_boolean_test
#define src_insn_supports_execution_test  x64_insn_supports_execution_test
#define src_insn_symbols_are_contained_in_map x64_insn_symbols_are_contained_in_map
#define src_insn_put_jump_to_nextpc x64_insn_put_jump_to_nextpc
#define src_insn_get_pcrel_values   x64_insn_get_pcrel_values
#define src_insn_set_pcrel_values   x64_insn_set_pcrel_values
#define src_insn_get_pcrel_operands x64_insn_get_pcrel_operands
#define src_insn_inv_rename_registers        x64_insn_inv_rename_registers
#define src_insn_inv_rename_memory_operands  x64_insn_inv_rename_memory_operands
#define src_insn_inv_rename_constants        x64_insn_inv_rename_constants
#define symbol_is_contained_in_src_insn      symbol_is_contained_in_x64_insn
#define src_insn_add_to_pcrels      x64_insn_add_to_pcrels
#define src_insn_canonicalize       x64_insn_canonicalize
#define src_insn_is_conditional_direct_branch x64_insn_is_conditional_direct_branch
#define src_init                 x64_init
#define src_insn_disassemble     x64_insn_disassemble
#define src_infer_regcons_from_assembly x64_infer_regcons_from_assembly
#define src_assemble x64_assemble
#define src_insn_get_constant_operand x64_insn_get_constant_operand
#define SRC_NOP_INSN_SIZE          1
#define src_insn_put_nop           x64_insn_put_nop
#define src_insn_put_move_imm_to_mem x64_insn_put_move_imm_to_mem
#define src_insn_type_signature_supported x64_insn_type_signature_supported
#define src_insn_put_nop_as        x64_insn_put_nop_as
#define src_insn_put_linux_exit_syscall_as x64_insn_put_linux_exit_syscall_as
#define src_iseq_rename_regs_and_imms x64_iseq_rename_regs_and_imms
#define src_regset_live_at_jumptable x64_regset_live_at_jumptable
#define src_strict_canonicalization_state_t x64_strict_canonicalization_state_t
#define src_strict_canonicalization_state_init x64_strict_canonicalization_state_init
#define src_strict_canonicalization_state_free x64_strict_canonicalization_state_free
#define src_insn_get_max_num_imm_operands x64_insn_get_max_num_imm_operands
#define src_pc_get_function_name_and_insn_num x64_pc_get_function_name_and_insn_num
#define src_insn_put_function_return         x64_insn_put_function_return
#define src_insn_put_invalid                 x64_insn_put_invalid
#define src_insn_put_ret_insn                x64_insn_put_ret_insn
#define src_insn_rename_constants            x64_insn_rename_constants
#define src_iseq_stores_eq_comparison_in_reg x64_iseq_stores_eq_comparison_in_reg
#define src_iseq_stores_ult_comparison_in_reg x64_iseq_stores_ult_comparison_in_reg
#define src_iseq_stores_slt_comparison_in_reg x64_iseq_stores_slt_comparison_in_reg
#define src_iseq_stores_ugt_comparison_in_reg x64_iseq_stores_ugt_comparison_in_reg
#define src_iseq_stores_sgt_comparison_in_reg x64_iseq_stores_sgt_comparison_in_reg
#define src_iseq_involves_cbranch x64_iseq_involves_cbranch
#define src_iseq_is_function_tailcall_opt_candidate x64_iseq_is_function_tailcall_opt_candidate
#define src_iseq_with_relocs_to_string     x64_iseq_with_relocs_to_string
#define src_insn_convert_pcrels_and_symbols_to_reloc_strings   x64_insn_convert_pcrels_and_symbols_to_reloc_strings
#define src_identity_regmap        x64_identity_regmap
#define src_iseq_rename            x64_iseq_rename
#define src_insn_inv_rename_registers        x64_insn_inv_rename_registers
#define src_insn_inv_rename_memory_operands  x64_insn_inv_rename_memory_operands

#else
#error "ARCH_SRC not specified"
#endif

#if ARCH_DST == ARCH_I386

#define DST_NUM_EXREG_GROUPS             I386_NUM_EXREG_GROUPS
#define DST_MAX_NUM_OPERANDS             I386_MAX_NUM_OPERANDS
#define DST_NUM_EXREGS                   I386_NUM_EXREGS
//#define DST_NUM_AVAILABLE_EXREGS         I386_NUM_AVAILABLE_EXREGS
#define DST_EXREG_LEN                    I386_EXREG_LEN
#define DST_NUM_INVISIBLE_REGS           I386_NUM_INVISIBLE_REGS
#define DST_INVISIBLE_REGS_LEN           I386_INVISIBLE_REGS_LEN
#define DST_ENV_EXOFF                    I386_ENV_EXOFF
#define DST_EXREG_GROUP_GPRS             I386_EXREG_GROUP_GPRS
#define DST_EXREG_GROUP_FLOAT_REGS       I386_EXREG_GROUP_FP_DATA_REGS
#define DST_MEM_TO_REG_COST              I386_MEM_TO_REG_COST
#define DST_REG_TO_MEM_COST              I386_REG_TO_MEM_COST
#define DST_REG_TO_EXREG_COST            I386_REG_TO_EXREG_COST
#define DST_AVG_REG_MOVE_COST_FOR_LOOP_EDGE_AND_ZERO_DEAD_REGS I386_AVG_REG_MOVE_COST_FOR_LOOP_EDGE_AND_ZERO_DEAD_REGS
#define DST_EXREG_TO_REG_COST            I386_EXREG_TO_REG_COST
#define DST_MEM_TO_EXREG_COST            I386_MEM_TO_EXREG_COST
#define DST_EXREG_TO_MEM_COST            I386_EXREG_TO_MEM_COST
#define DST_EXREG_MODIFIER_TRANSLATION_COST I386_EXREG_MODIFIER_TRANSLATION_COST
#define DST_EXREG_TO_EXREG_COST          I386_EXREG_TO_EXREG_COST
#define dst_insn_t                   i386_insn_t
#define dst_iseq_to_string               i386_iseq_to_string
#define dst_insn_to_string               i386_insn_to_string
#define dst_insn_copy                    i386_insn_copy
#define dst_iseq_copy                    i386_iseq_copy
//#define dst_insn_init                    i386_insn_init
#define dst_iseq_compute_execution_cost            i386_iseq_compute_execution_cost
//#define dst_iseq_from_string             i386_iseq_from_string
#define dst_infer_regcons_from_assembly  i386_infer_regcons_from_assembly
#define dst_iseq_get_touch_not_live_in_regs   i386_iseq_get_touch_not_live_in_regs
#define dst_iseq_with_relocs_to_string   i386_iseq_with_relocs_to_string
#define dst_iseq_rename                  i386_iseq_rename
#define dst_iseq_rename_var              i386_iseq_rename_var
#define dst_insn_put_move_mem_to_mem     i386_insn_put_move_mem_to_mem
#define dst_insn_put_move_reg_to_mem     i386_insn_put_movl_reg_to_mem
#define dst_insn_put_move_exreg_to_mem   i386_insn_put_move_exreg_to_mem
#define dst_insn_put_move_reg_to_reg     i386_insn_put_movl_reg_to_reg
#define dst_insn_put_move_exreg_to_exreg i386_insn_put_move_exreg_to_exreg
#define dst_insn_put_move_exreg_to_reg   i386_insn_put_move_exreg_to_reg
#define dst_insn_put_move_reg_to_exreg   i386_insn_put_move_reg_to_exreg
#define dst_insn_put_move_exreg_to_mem   i386_insn_put_move_exreg_to_mem
#define dst_insn_put_move_mem_to_exreg   i386_insn_put_move_mem_to_exreg
#define dst_insn_put_move_mem_to_reg     i386_insn_put_movl_mem_to_reg
#define dst_insn_put_xchg_reg_with_reg   i386_insn_put_xchg_reg_with_reg
#define dst_insn_put_xchg_reg_with_reg_var   i386_insn_put_xchg_reg_with_reg_var
#define dst_insn_put_xchg_exreg_with_exreg i386_insn_put_xchg_exreg_with_exreg
//#define dst_iseq_matches_template        i386_iseq_matches_template
//#define dst_iseq_matches_template_var    i386_iseq_matches_template_var
#define dst_insn_type_signature_supported i386_insn_type_signature_supported
#define dst_insn_fetch_raw               i386_insn_fetch_raw
//#define dst_iseq_strict_canonicalize     i386_iseq_strict_canonicalize
#define dst_num_costfns                  i386_num_costfns
#define dst_costfns                      i386_costfns
#define dst_costfn_t                     i386_costfn_t
//#define dst_iseq_connect_end_points       i386_iseq_connect_end_points
#define dst_insn_is_unconditional_direct_branch i386_insn_is_unconditional_direct_branch
#define dst_insn_is_unconditional_branch_not_fcall i386_insn_is_unconditional_branch_not_fcall
#define dst_insn_is_unconditional_indirect_branch_not_fcall i386_insn_is_unconditional_indirect_branch_not_fcall
#define dst_insn_is_branch_not_fcall     i386_insn_is_branch_not_fcall
#define dst_insn_is_conditional_direct_branch i386_insn_is_conditional_direct_branch
#define dst_insn_is_conditional_indirect_branch i386_insn_is_conditional_indirect_branch
#define dst_insn_branch_target_src_insn_pc i386_insn_branch_target_src_insn_pc
#define dst_insn_get_pcrel_operands      i386_insn_get_pcrel_operands
#define dst_iseq_assemble                i386_iseq_assemble
#define dst_assemble                     x86_assemble
#define regcons_set_dst                  regcons_set_i386
#define dst_transmap_default             i386_transmap_default
#define dst_iseq_compute_num_nextpcs     i386_iseq_compute_num_nextpcs
#define dst_insn_is_nop                  i386_insn_is_nop
#define dst_init                         i386_init
#define dst_free                         i386_free
#define dst_iseq_contains_reloc_reference i386_iseq_contains_reloc_reference
#define dst_insn_supports_boolean_test   i386_insn_supports_boolean_test
#define dst_insn_canonicalize            i386_insn_canonicalize
#define dst_insns_equal                  i386_insns_equal
#define dst_iseq_mark_used_vconstants    i386_iseq_mark_used_vconstants
#define dst_insn_is_direct_branch        i386_insn_is_direct_branch
#define dst_insn_is_lea                  i386_insn_is_lea
#define regmap_identity_for_dst          regmap_identity_for_i386
//#define dst_iseq_sandbox                 i386_iseq_sandbox
#define dst_insn_rename_constants        i386_insn_rename_constants
#define dst_insn_put_jump_to_nextpc      i386_insn_put_jump_to_nextpc
#define dst_insn_put_jump_to_abs_inum    i386_insn_put_jump_to_abs_inum
#define dst_insn_put_jump_to_src_insn_pc i386_insn_put_jump_to_src_insn_pc
#define dst_insn_put_jump_to_pcrel       i386_insn_put_jump_to_pcrel
//#define dst_iseq_make_position_independent i386_iseq_make_position_independent
#define dst_iseq_rename_nextpc_consts    i386_iseq_rename_nextpc_consts
#define dst_iseq_get_used_vconst_regs    i386_iseq_get_used_vconst_regs
#define dst_assemble_exec_iseq_using_regmap i386_assemble_exec_iseq_using_regmap
#define dst_insn_get_pcrel_values        i386_insn_get_pcrel_values
#define dst_insn_set_pcrel_values        i386_insn_set_pcrel_values
#define dst_insn_is_indirect_branch      i386_insn_is_indirect_branch
#define dst_iseq_supports_execution_test i386_iseq_supports_execution_test
//#define dst_iseq_rename_vconsts          i386_iseq_rename_vconsts
#define dst_insn_is_intdiv                  i386_insn_is_intdiv
#define dst_insn_to_int_array            i386_insn_to_int_array
//#define dst_iseq_convert_pcs_to_inums    i386_iseq_convert_pcs_to_inums
#define dst_insn_is_function_call        i386_insn_is_function_call
//#define dst_iseq_disassemble             i386_iseq_disassemble
#define dst_iseq_types_equal             i386_iseq_types_equal
#define dst_insn_put_movl_nextpc_constant_to_mem i386_insn_put_movl_nextpc_constant_to_mem
#define dst_insn_put_jump_to_indir_mem   i386_insn_put_jump_to_indir_mem
#define DST_NUM_GPRS                     I386_NUM_GPRS
#define dst_insn_put_movl_reg_var_to_mem i386_insn_put_movl_reg_var_to_mem
#define dst_insn_put_movl_mem_to_reg_var i386_insn_put_movl_mem_to_reg_var
#define dst_insn_put_move_imm_to_reg     i386_insn_put_movl_imm_to_reg
#define dst_insn_sandbox                 i386_insn_sandbox
#define dst_operand_strict_canonicalize_regs i386_operand_strict_canonicalize_regs
#define dst_operand_strict_canonicalize_imms i386_operand_strict_canonicalize_imms
#define dst_memtouch_strict_canonicalize     i386_memtouch_strict_canonicalize
//#define disas_insn_dst                   disas_insn_i386
#define dst_insn_add_to_pcrels           i386_insn_add_to_pcrels
#define dst_insn_add_implicit_operands   i386_insn_add_implicit_operands
#define dst_insn_disassemble            i386_insn_disassemble
#define dst_insn_inv_rename_registers        i386_insn_inv_rename_registers
#define dst_insn_inv_rename_memory_operands  i386_insn_inv_rename_memory_operands
#define dst_insn_inv_rename_constants        i386_insn_inv_rename_constants
#define dst_assemble                         x86_assemble
#define dst_exregname_suffix                 i386_exregname_suffix
#define dst_insn_inv_rename_locals_symbols   i386_insn_inv_rename_locals_symbols
//#define dst_insn_rename_nextpcs              i386_insn_rename_nextpcs
#define dst_insn_symbols_are_contained_in_map i386_insn_symbols_are_contained_in_map
#define symbol_is_contained_in_dst_insn      symbol_is_contained_in_i386_insn
#define dst_insn_rename_symbols_to_addresses i386_insn_rename_symbols_to_addresses
//#define dst_iseq_hash_func         i386_iseq_hash_func
#define dst_insn_hash_canonicalize i386_insn_hash_canonicalize
#define dst_insn_put_nop           i386_insn_put_nop
#define dst_insn_rename_immediate_operands_containing_code_addresses i386_insn_rename_immediate_operands_containing_code_addresses
#define dst_insn_gen_sym_exec_reader_file i386_insn_gen_sym_exec_reader_file
#define dst_insn_hash_func       i386_insn_hash_func
#define dst_insn_is_function_return i386_insn_is_function_return
#define dst_insn_canonicalize_locals_symbols i386_insn_canonicalize_locals_symbols
#define dst_strict_canonicalization_state_t i386_strict_canonicalization_state_t
#define dst_strict_canonicalization_state_init i386_strict_canonicalization_state_init
#define dst_strict_canonicalization_state_free i386_strict_canonicalization_state_free
#define dst_insn_get_max_num_imm_operands i386_insn_get_max_num_imm_operands
#define dst_pc_get_function_name_and_insn_num i386_pc_get_function_name_and_insn_num
#define DST_FASTCALL_NUM_REGPARAMS I386_FASTCALL_NUM_REGPARAMS
#define DST_FASTCALL_REGPARAM I386_FASTCALL_REGPARAM
#define DST_FASTCALL_NUM_REGPARAMS_EXT I386_FASTCALL_NUM_REGPARAMS_EXT
#define DST_FASTCALL_REGPARAM_EXT I386_FASTCALL_REGPARAM_EXT
#define DST_FASTCALL_NUM_RETREGS I386_FASTCALL_NUM_RETREGS
#define DST_FASTCALL_RETREG I386_FASTCALL_RETREG
#define dst_insn_set_nextpc        i386_insn_set_nextpc
#define dst_iseq_inv_rename_imms_using_imm_vt_map i386_iseq_inv_rename_imms_using_imm_vt_map
#define dst_iseq_rename_nextpc_vars_to_pcrel_relocs i386_iseq_rename_nextpc_vars_to_pcrel_relocs
#define dst_reserved_regs i386_reserved_regs
#define dst_insn_put_xchg_reg_with_mem i386_insn_put_xchg_reg_with_mem
#define dst_insn_put_add_imm_with_reg i386_insn_put_add_imm_with_reg
#define DST_STACK_REGNUM R_ESP
#define dst_callee_save_regs i386_callee_save_regs
#define dst_iseq_rename_locals_using_locals_map i386_iseq_rename_locals_using_locals_map
#define dst_iseq_replace_tmap_loc_with_const i386_iseq_replace_tmap_loc_with_const
#define dst_iseq_rename_randomly_and_assemble i386_iseq_rename_randomly_and_assemble
#define dst_insn_put_zextend_exreg i386_insn_put_zextend_exreg
#define dst_emit_translation_marker_insns    i386_emit_translation_marker_insns
#define dst_iseq_has_marker_prefix           i386_iseq_has_marker_prefix
#define dst_insn_rename_cregs_to_vregs       i386_insn_rename_cregs_to_vregs
#define dst_insn_rename_vregs_to_cregs       i386_insn_rename_vregs_to_cregs
#define dst_enumerate_in_out_transmaps_for_usedef i386_enumerate_in_out_transmaps_for_usedef
//#define dst_iseq_hash_func_after_canon  i386_iseq_hash_func_after_canon
#define dst_iseq_convert_peeptab_mem_constants_to_symbols i386_iseq_convert_peeptab_mem_constants_to_symbols
#define dst_insn_rename_vregs_using_regmap    i386_insn_rename_vregs_using_regmap
#define dst_opcodes_related    i386_opcodes_related
#define dst_insn_rename_memory_operand_to_symbol  i386_insn_rename_memory_operand_to_symbol
#define dst_iseq_count_touched_regs_as_cost i386_iseq_count_touched_regs_as_cost
#define dst_insn_rename_tag_src_insn_pcs_to_tag_vars i386_insn_rename_tag_src_insn_pcs_to_tag_vars
#define dst_insn_rename_tag_src_insn_pcs_to_tag_var_using_tcodes i386_insn_rename_tag_src_insn_pcs_to_tag_var_using_tcodes
#define dst_insn_rename_tag_src_insn_pcs_to_dst_pcrels_using_tinsns_map i386_insn_rename_tag_src_insn_pcs_to_dst_pcrels_using_tinsns_map
#define dst_insn_is_move_insn                  i386_insn_is_move_insn
#define dst_insn_rename_defed_reg          i386_insn_rename_defed_reg
#define dst_iseq_is_well_formed            i386_iseq_is_well_formed
#define dst_insn_rename_regs               i386_insn_rename_regs
#define dst_insn_reg_is_replaceable        i386_insn_reg_is_replaceable
#define dst_insn_reg_def_is_replaceable    i386_insn_reg_def_is_replaceable
#define dst_insn_rename_dst_reg            i386_insn_rename_dst_reg
#define dst_insn_invert_branch_condition   i386_insn_invert_branch_condition
#define dst_insn_deallocates_stack         i386_insn_deallocates_stack
#define dst_insn_convert_function_call_to_branch i386_insn_convert_function_call_to_branch
#define dst_insn_put_function_return       i386_insn_put_function_return
#define dst_identity_regmap                i386_identity_regmap
#define dst_insn_convert_malloc_to_mymalloc i386_insn_convert_malloc_to_mymalloc

#elif ARCH_DST == ARCH_X64

#define DST_NUM_EXREG_GROUPS             X64_NUM_EXREG_GROUPS
#define DST_MAX_NUM_OPERANDS             X64_MAX_NUM_OPERANDS
#define DST_NUM_EXREGS                   X64_NUM_EXREGS
#define DST_EXREG_LEN                    X64_EXREG_LEN
#define DST_NUM_INVISIBLE_REGS           X64_NUM_INVISIBLE_REGS
#define DST_INVISIBLE_REGS_LEN           X64_INVISIBLE_REGS_LEN
#define DST_ENV_EXOFF                    X64_ENV_EXOFF
#define DST_EXREG_GROUP_GPRS             X64_EXREG_GROUP_GPRS
#define DST_EXREG_GROUP_FLOAT_REGS       X64_EXREG_GROUP_FP_DATA_REGS
#define DST_MEM_TO_REG_COST              X64_MEM_TO_REG_COST
#define DST_REG_TO_MEM_COST              X64_REG_TO_MEM_COST
#define DST_REG_TO_EXREG_COST            X64_REG_TO_EXREG_COST
#define DST_AVG_REG_MOVE_COST_FOR_LOOP_EDGE_AND_ZERO_DEAD_REGS X64_AVG_REG_MOVE_COST_FOR_LOOP_EDGE_AND_ZERO_DEAD_REGS
#define DST_EXREG_TO_REG_COST            X64_EXREG_TO_REG_COST
#define DST_MEM_TO_EXREG_COST            X64_MEM_TO_EXREG_COST
#define DST_EXREG_TO_MEM_COST            X64_EXREG_TO_MEM_COST
#define DST_EXREG_MODIFIER_TRANSLATION_COST X64_EXREG_MODIFIER_TRANSLATION_COST
#define DST_EXREG_TO_EXREG_COST          X64_EXREG_TO_EXREG_COST
#define dst_insn_t                   x64_insn_t
#define dst_iseq_to_string               x64_iseq_to_string
#define dst_insn_to_string               x64_insn_to_string
#define dst_insn_copy                    x64_insn_copy
#define dst_iseq_copy                    x64_iseq_copy
//#define dst_insn_init                    x64_insn_init
#define dst_iseq_compute_execution_cost            x64_iseq_compute_execution_cost
#define dst_infer_regcons_from_assembly  x64_infer_regcons_from_assembly
#define dst_iseq_get_touch_not_live_in_regs   x64_iseq_get_touch_not_live_in_regs
#define dst_iseq_with_relocs_to_string   x64_iseq_with_relocs_to_string
#define dst_iseq_rename                  x64_iseq_rename
#define dst_iseq_rename_var              x64_iseq_rename_var
#define dst_insn_put_move_mem_to_mem     x64_insn_put_move_mem_to_mem
#define dst_insn_put_move_reg_to_mem     x64_insn_put_movl_reg_to_mem
#define dst_insn_put_move_exreg_to_mem   x64_insn_put_move_exreg_to_mem
#define dst_insn_put_move_reg_to_reg     x64_insn_put_movl_reg_to_reg
#define dst_insn_put_move_exreg_to_exreg x64_insn_put_move_exreg_to_exreg
#define dst_insn_put_move_exreg_to_reg   x64_insn_put_move_exreg_to_reg
#define dst_insn_put_move_reg_to_exreg   x64_insn_put_move_reg_to_exreg
#define dst_insn_put_move_exreg_to_mem   x64_insn_put_move_exreg_to_mem
#define dst_insn_put_move_mem_to_exreg   x64_insn_put_move_mem_to_exreg
#define dst_insn_put_move_mem_to_reg     x64_insn_put_movl_mem_to_reg
#define dst_insn_put_xchg_reg_with_reg   x64_insn_put_xchg_reg_with_reg
#define dst_insn_put_xchg_reg_with_reg_var   x64_insn_put_xchg_reg_with_reg_var
#define dst_insn_put_xchg_exreg_with_exreg x64_insn_put_xchg_exreg_with_exreg
#define dst_insn_type_signature_supported x64_insn_type_signature_supported
#define dst_insn_fetch_raw               x64_insn_fetch_raw
#define dst_num_costfns                  x64_num_costfns
#define dst_costfns                      x64_costfns
#define dst_costfn_t                     x64_costfn_t
#define dst_insn_is_unconditional_direct_branch x64_insn_is_unconditional_direct_branch
#define dst_insn_is_unconditional_branch_not_fcall x64_insn_is_unconditional_branch_not_fcall
#define dst_insn_is_unconditional_indirect_branch_not_fcall x64_insn_is_unconditional_indirect_branch_not_fcall
#define dst_insn_is_branch_not_fcall     x64_insn_is_branch_not_fcall
#define dst_insn_is_conditional_direct_branch x64_insn_is_conditional_direct_branch
#define dst_insn_is_conditional_indirect_branch x64_insn_is_conditional_indirect_branch
#define dst_insn_branch_target_src_insn_pc x64_insn_branch_target_src_insn_pc
#define dst_insn_get_pcrel_operands      x64_insn_get_pcrel_operands
#define dst_iseq_assemble                x64_iseq_assemble
#define dst_assemble                     x64_assemble
#define regcons_set_dst                  regcons_set_x64
#define dst_transmap_default             x64_transmap_default
#define dst_iseq_compute_num_nextpcs     x64_iseq_compute_num_nextpcs
#define dst_insn_is_nop                  x64_insn_is_nop
#define dst_init                         x64_init
#define dst_free                         x64_free
#define dst_iseq_contains_reloc_reference x64_iseq_contains_reloc_reference
#define dst_insn_supports_boolean_test   x64_insn_supports_boolean_test
#define dst_insn_canonicalize            x64_insn_canonicalize
#define dst_insns_equal                  x64_insns_equal
#define dst_iseq_mark_used_vconstants    x64_iseq_mark_used_vconstants
#define dst_insn_is_direct_branch        x64_insn_is_direct_branch
#define dst_insn_is_lea                  x64_insn_is_lea
#define regmap_identity_for_dst          regmap_identity_for_x64
#define dst_insn_rename_constants        x64_insn_rename_constants
#define dst_insn_put_jump_to_nextpc      x64_insn_put_jump_to_nextpc
#define dst_insn_put_jump_to_abs_inum    x64_insn_put_jump_to_abs_inum
#define dst_insn_put_jump_to_src_insn_pc x64_insn_put_jump_to_src_insn_pc
#define dst_insn_put_jump_to_pcrel       x64_insn_put_jump_to_pcrel
#define dst_iseq_rename_nextpc_consts    x64_iseq_rename_nextpc_consts
#define dst_iseq_get_used_vconst_regs    x64_iseq_get_used_vconst_regs
#define dst_assemble_exec_iseq_using_regmap x64_assemble_exec_iseq_using_regmap
#define dst_insn_get_pcrel_values        x64_insn_get_pcrel_values
#define dst_insn_set_pcrel_values        x64_insn_set_pcrel_values
#define dst_insn_is_indirect_branch      x64_insn_is_indirect_branch
#define dst_iseq_supports_execution_test x64_iseq_supports_execution_test
#define dst_insn_is_intdiv               x64_insn_is_intdiv
#define dst_insn_to_int_array            x64_insn_to_int_array
#define dst_insn_is_function_call        x64_insn_is_function_call
#define dst_iseq_types_equal             x64_iseq_types_equal
#define dst_insn_put_movl_nextpc_constant_to_mem x64_insn_put_movl_nextpc_constant_to_mem
#define dst_insn_put_jump_to_indir_mem   x64_insn_put_jump_to_indir_mem
#define DST_NUM_GPRS                     X64_NUM_GPRS
#define dst_insn_put_movl_reg_var_to_mem x64_insn_put_movl_reg_var_to_mem
#define dst_insn_put_movl_mem_to_reg_var x64_insn_put_movl_mem_to_reg_var
#define dst_insn_put_move_imm_to_reg     x64_insn_put_movl_imm_to_reg
#define dst_insn_sandbox                 x64_insn_sandbox
#define dst_operand_strict_canonicalize_regs x64_operand_strict_canonicalize_regs
#define dst_operand_strict_canonicalize_imms x64_operand_strict_canonicalize_imms
#define dst_memtouch_strict_canonicalize     x64_memtouch_strict_canonicalize
#define dst_insn_add_to_pcrels           x64_insn_add_to_pcrels
#define dst_insn_add_implicit_operands   x64_insn_add_implicit_operands
#define dst_insn_disassemble            x64_insn_disassemble
#define dst_insn_inv_rename_registers        x64_insn_inv_rename_registers
#define dst_insn_inv_rename_memory_operands  x64_insn_inv_rename_memory_operands
#define dst_insn_inv_rename_constants        x64_insn_inv_rename_constants
#define dst_assemble                         x64_assemble
#define dst_exregname_suffix                 x64_exregname_suffix
#define dst_insn_inv_rename_locals_symbols   x64_insn_inv_rename_locals_symbols
#define dst_insn_symbols_are_contained_in_map x64_insn_symbols_are_contained_in_map
#define symbol_is_contained_in_dst_insn      symbol_is_contained_in_x64_insn
#define dst_insn_rename_symbols_to_addresses x64_insn_rename_symbols_to_addresses
#define dst_insn_hash_canonicalize x64_insn_hash_canonicalize
#define dst_insn_put_nop           x64_insn_put_nop
#define dst_insn_rename_immediate_operands_containing_code_addresses x64_insn_rename_immediate_operands_containing_code_addresses
#define dst_insn_gen_sym_exec_reader_file x64_insn_gen_sym_exec_reader_file
#define dst_insn_hash_func       x64_insn_hash_func
#define dst_insn_is_function_return x64_insn_is_function_return
#define dst_insn_canonicalize_locals_symbols x64_insn_canonicalize_locals_symbols
#define dst_strict_canonicalization_state_t x64_strict_canonicalization_state_t
#define dst_strict_canonicalization_state_init x64_strict_canonicalization_state_init
#define dst_strict_canonicalization_state_free x64_strict_canonicalization_state_free
#define dst_insn_get_max_num_imm_operands x64_insn_get_max_num_imm_operands
#define dst_pc_get_function_name_and_insn_num x64_pc_get_function_name_and_insn_num
#define DST_FASTCALL_NUM_REGPARAMS X64_FASTCALL_NUM_REGPARAMS
#define DST_FASTCALL_REGPARAM X64_FASTCALL_REGPARAM
#define DST_FASTCALL_NUM_REGPARAMS_EXT X64_FASTCALL_NUM_REGPARAMS_EXT
#define DST_FASTCALL_REGPARAM_EXT X64_FASTCALL_REGPARAM_EXT
#define DST_FASTCALL_NUM_RETREGS X64_FASTCALL_NUM_RETREGS
#define DST_FASTCALL_RETREG X64_FASTCALL_RETREG
#define dst_insn_set_nextpc        x64_insn_set_nextpc
#define dst_iseq_inv_rename_imms_using_imm_vt_map x64_iseq_inv_rename_imms_using_imm_vt_map
#define dst_iseq_rename_nextpc_vars_to_pcrel_relocs x64_iseq_rename_nextpc_vars_to_pcrel_relocs
#define dst_reserved_regs x64_reserved_regs
#define dst_insn_put_xchg_reg_with_mem x64_insn_put_xchg_reg_with_mem
#define dst_insn_put_add_imm_with_reg x64_insn_put_add_imm_with_reg
#define DST_STACK_REGNUM R_ESP
#define dst_callee_save_regs x64_callee_save_regs
#define dst_iseq_rename_locals_using_locals_map x64_iseq_rename_locals_using_locals_map
#define dst_iseq_replace_tmap_loc_with_const x64_iseq_replace_tmap_loc_with_const
#define dst_iseq_rename_randomly_and_assemble x64_iseq_rename_randomly_and_assemble
#define dst_insn_put_zextend_exreg x64_insn_put_zextend_exreg
#define dst_emit_translation_marker_insns    x64_emit_translation_marker_insns
#define dst_iseq_has_marker_prefix           x64_iseq_has_marker_prefix
#define dst_insn_rename_cregs_to_vregs       x64_insn_rename_cregs_to_vregs
#define dst_insn_rename_vregs_to_cregs       x64_insn_rename_vregs_to_cregs
#define dst_enumerate_in_out_transmaps_for_usedef x64_enumerate_in_out_transmaps_for_usedef
#define dst_iseq_convert_peeptab_mem_constants_to_symbols x64_iseq_convert_peeptab_mem_constants_to_symbols
#define dst_insn_rename_vregs_using_regmap    x64_insn_rename_vregs_using_regmap
#define dst_opcodes_related    x64_opcodes_related
#define dst_insn_rename_memory_operand_to_symbol  x64_insn_rename_memory_operand_to_symbol
#define dst_iseq_count_touched_regs_as_cost x64_iseq_count_touched_regs_as_cost
#define dst_insn_rename_tag_src_insn_pcs_to_tag_vars x64_insn_rename_tag_src_insn_pcs_to_tag_vars
#define dst_insn_rename_tag_src_insn_pcs_to_tag_var_using_tcodes x64_insn_rename_tag_src_insn_pcs_to_tag_var_using_tcodes
#define dst_insn_rename_tag_src_insn_pcs_to_dst_pcrels_using_tinsns_map x64_insn_rename_tag_src_insn_pcs_to_dst_pcrels_using_tinsns_map
#define dst_insn_is_move_insn                  x64_insn_is_move_insn
#define dst_insn_rename_defed_reg          x64_insn_rename_defed_reg
#define dst_iseq_is_well_formed            x64_iseq_is_well_formed
#define dst_insn_rename_regs               x64_insn_rename_regs
#define dst_insn_reg_is_replaceable        x64_insn_reg_is_replaceable
#define dst_insn_reg_def_is_replaceable    x64_insn_reg_def_is_replaceable
#define dst_insn_rename_dst_reg            x64_insn_rename_dst_reg
#define dst_insn_invert_branch_condition   x64_insn_invert_branch_condition
#define dst_insn_deallocates_stack         x64_insn_deallocates_stack
#define dst_insn_convert_function_call_to_branch x64_insn_convert_function_call_to_branch
#define dst_insn_put_function_return       x64_insn_put_function_return
#define dst_identity_regmap                x64_identity_regmap
#define dst_insn_convert_malloc_to_mymalloc x64_insn_convert_malloc_to_mymalloc

#elif ARCH_DST == ARCH_PPC

#define DST_NUM_EXREG_GROUPS             PPC_NUM_EXREG_GROUPS
#define DST_MAX_NUM_OPERANDS             PPC_MAX_NUM_OPERANDS
#define DST_NUM_EXREGS                   PPC_NUM_EXREGS
#define DST_EXREG_LEN                    PPC_EXREG_LEN
#define DST_NUM_INVISIBLE_REGS           PPC_NUM_INVISIBLE_REGS
#define DST_INVISIBLE_REGS_LEN           PPC_INVISIBLE_REGS_LEN
#define DST_ENV_EXOFF                    PPC_ENV_EXOFF
#define DST_EXREG_GROUP_GPRS             PPC_EXREG_GROUP_GPRS
#define DST_MEM_TO_REG_COST              PPC_MEM_TO_REG_COST
#define DST_REG_TO_MEM_COST              PPC_REG_TO_MEM_COST
#define DST_REG_TO_EXREG_COST            PPC_REG_TO_EXREG_COST
#define DST_AVG_REG_MOVE_COST_FOR_LOOP_EDGE_AND_ZERO_DEAD_REGS PPC_AVG_REG_MOVE_COST_FOR_LOOP_EDGE_AND_ZERO_DEAD_REGS
#define DST_EXREG_TO_REG_COST            PPC_EXREG_TO_REG_COST
#define DST_MEM_TO_EXREG_COST            PPC_MEM_TO_EXREG_COST
#define DST_EXREG_TO_MEM_COST            PPC_EXREG_TO_MEM_COST
#define DST_EXREG_TO_EXREG_COST          PPC_EXREG_TO_EXREG_COST
#define dst_insn_t                       ppc_insn_t
#define dst_iseq_to_string               ppc_iseq_to_string
#define dst_insn_to_string               ppc_insn_to_string
#define dst_insn_copy                    ppc_insn_copy
#define dst_iseq_copy                    ppc_iseq_copy
//#define dst_insn_init                    ppc_insn_init
#define dst_iseq_compute_execution_cost            ppc_iseq_compute_cost
//#define dst_iseq_from_string             ppc_iseq_from_string
#define dst_infer_regcons_from_assembly  ppc_infer_regcons_from_assembly
#define dst_iseq_get_touch_not_live_in_regs   ppc_iseq_get_touch_not_live_in_regs
#define dst_iseq_with_relocs_to_string   ppc_iseq_with_relocs_to_string
#define dst_iseq_rename                  ppc_iseq_rename
#define dst_iseq_rename_var              ppc_iseq_rename_var
#define dst_insn_put_move_mem_to_mem     ppc_insn_put_move_mem_to_mem
#define dst_insn_put_move_reg_to_mem     ppc_insn_put_movl_reg_to_mem
#define dst_insn_put_move_exreg_to_mem   ppc_insn_put_move_exreg_to_mem
#define dst_insn_put_move_reg_to_reg     ppc_insn_put_movl_reg_to_reg
#define dst_insn_put_move_exreg_to_exreg ppc_insn_put_move_exreg_to_exreg
#define dst_insn_put_move_exreg_to_reg   ppc_insn_put_move_exreg_to_reg
#define dst_insn_put_move_reg_to_exreg   ppc_insn_put_move_reg_to_exreg
#define dst_insn_put_move_exreg_to_mem   ppc_insn_put_move_exreg_to_mem
#define dst_insn_put_move_mem_to_exreg   ppc_insn_put_move_mem_to_exreg
#define dst_insn_put_move_mem_to_reg     ppc_insn_put_movl_mem_to_reg
#define dst_insn_put_xchg_reg_with_reg   ppc_insn_put_xchg_reg_with_reg
#define dst_insn_put_xchg_exreg_with_exreg ppc_insn_put_xchg_exreg_with_exreg
//#define dst_iseq_matches_template_var    ppc_iseq_matches_template_var
#define dst_iseq_matches_template        ppc_iseq_matches_template
#define dst_insn_type_signature_supported ppc_insn_type_signature_supported
#define dst_insn_fetch_raw               ppc_insn_fetch_raw
//#define dst_iseq_strict_canonicalize     ppc_iseq_strict_canonicalize
#define dst_num_costfns                  ppc_num_costfns
#define dst_costfns                      ppc_costfns
#define dst_costfn_t                     ppc_costfn_t
//#define dst_iseq_connect_end_points      ppc_iseq_connect_end_points
#define dst_insn_is_unconditional_direct_branch ppc_insn_is_unconditional_direct_branch
#define dst_insn_is_unconditional_branch_not_fcall ppc_insn_is_unconditional_branch_not_fcall
#define dst_insn_is_unconditional_indirect_branch_not_fcall ppc_insn_is_unconditional_indirect_branch_not_fcall
#define dst_insn_is_branch_not_fcall     ppc_insn_is_branch_not_fcall
#define dst_insn_is_conditional_direct_branch ppc_insn_is_conditional_direct_branch
#define dst_insn_is_conditional_indirect_branch ppc_insn_is_conditional_indirect_branch
#define dst_insn_branch_target_src_insn_pc  ppc_insn_branch_target_src_insn_pc
#define dst_insn_get_pcrel_operands      ppc_insn_get_pcrel_operands
#define dst_iseq_assemble                ppc_iseq_assemble
#define regcons_set_dst                  regcons_set_ppc
#define dst_transmap_default             ppc_transmap_default
#define dst_iseq_compute_num_nextpcs     ppc_iseq_compute_num_nextpcs
#define dst_insn_is_nop                  ppc_insn_is_nop
#define dst_init                         ppc_init
#define dst_free                         ppc_free
#define dst_iseq_contains_reloc_reference ppc_iseq_contains_reloc_reference
#define dst_insn_supports_boolean_test   ppc_insn_supports_boolean_test
#define dst_insn_canonicalize            ppc_insn_canonicalize
#define dst_insns_equal                  ppc_insns_equal
#define dst_iseq_mark_used_vconstants    ppc_iseq_mark_used_vconstants
#define dst_insn_is_direct_branch        ppc_insn_is_direct_branch
#define dst_insn_is_lea                  ppc_insn_is_lea
#define regmap_identity_for_dst          regmap_identity_for_ppc
//#define dst_iseq_sandbox                 ppc_iseq_sandbox
#define dst_insn_rename_constants        ppc_insn_rename_constants
#define dst_insn_put_jump_to_nextpc      ppc_insn_put_jump_to_nextpc
#define dst_insn_put_jump_to_pcrel       ppc_insn_put_jump_to_pcrel
#define dst_insn_put_jump_to_abs_inum    ppc_insn_put_jump_to_abs_inum
#define dst_insn_put_jump_to_src_insn_pc ppc_insn_put_jump_to_src_insn_pc
//#define dst_iseq_make_position_independent ppc_iseq_make_position_independent
#define dst_iseq_rename_nextpc_consts    ppc_iseq_rename_nextpc_consts
#define dst_iseq_get_used_vconst_regs    ppc_iseq_get_used_vconst_regs
#define dst_assemble_exec_iseq_using_regmap ppc_assemble_exec_iseq_using_regmap
#define dst_insn_get_pcrel_values        ppc_insn_get_pcrel_values
#define dst_insn_set_pcrel_values        ppc_insn_set_pcrel_values
#define dst_insn_is_indirect_branch      ppc_insn_is_indirect_branch
#define dst_iseq_supports_execution_test ppc_iseq_supports_execution_test
//#define dst_iseq_rename_vconsts          ppc_iseq_rename_vconsts
#define dst_insn_is_intdiv                  ppc_insn_is_intdiv
#define dst_insn_to_int_array            ppc_insn_to_int_array
//#define dst_iseq_convert_pcs_to_inums    ppc_iseq_convert_pcs_to_inums
#define dst_insn_is_function_call        ppc_insn_is_function_call
//#define dst_iseq_disassemble             ppc_iseq_disassemble
#define dst_iseq_types_equal             ppc_iseq_types_equal
#define dst_insn_put_movl_nextpc_constant_to_mem ppc_insn_put_movl_nextpc_constant_to_mem
#define dst_insn_put_jump_to_indir_mem   ppc_insn_put_jump_to_indir_mem
#define DST_NUM_GPRS                     PPC_NUM_GPRS
#define dst_insn_put_movl_reg_var_to_mem ppc_insn_put_movl_reg_var_to_mem
#define dst_insn_put_movl_mem_to_reg_var ppc_insn_put_movl_mem_to_reg_var
#define dst_insn_sandbox                ppc_insn_sandbox
#define dst_operand_strict_canonicalize_regs ppc_operand_strict_canonicalize_regs
#define dst_operand_strict_canonicalize_imms ppc_operand_strict_canonicalize_imms
#define dst_memtouch_strict_canonicalize     ppc_memtouch_strict_canonicalize
//#define disas_insn_dst                   disas_insn_ppc
#define dst_insn_add_to_pcrels           ppc_insn_add_to_pcrels
#define dst_insn_add_implicit_operands   ppc_insn_add_implicit_operands
#define dst_insn_disassemble            ppc_insn_disassemble
#define dst_insn_inv_rename_registers        ppc_insn_inv_rename_registers
#define dst_insn_inv_rename_memory_operands  ppc_insn_inv_rename_memory_operands
#define dst_insn_inv_rename_constants        ppc_insn_inv_rename_constants
#define dst_assemble                         ppc_assemble
#define dst_exregname_suffix                 ppc_exregname_suffix
#define dst_insn_inv_rename_locals_symbols   ppc_insn_inv_rename_locals_symbols
//#define dst_insn_rename_nextpcs              ppc_insn_rename_nextpcs
#define dst_insn_symbols_are_contained_in_map ppc_insn_symbols_are_contained_in_map
#define symbol_is_contained_in_dst_insn      symbol_is_contained_in_ppc_insn
#define dst_insn_rename_symbols_to_addresses ppc_insn_rename_symbols_to_addresses
//#define dst_iseq_hash_func         ppc_iseq_hash_func
#define dst_insn_hash_canonicalize ppc_insn_hash_canonicalize
#define dst_insn_put_nop           ppc_insn_put_nop
#define dst_insn_rename_immediate_operands_containing_code_addresses ppc_insn_rename_immediate_operands_containing_code_addresses
#define dst_insn_gen_sym_exec_reader_file ppc_insn_gen_sym_exec_reader_file
#define dst_insn_hash_func       ppc_insn_hash_func
#define dst_insn_is_function_return ppc_insn_is_function_return
#define dst_insn_canonicalize_locals_symbols ppc_insn_canonicalize_locals_symbols
#define dst_strict_canonicalization_state_t ppc_strict_canonicalization_state_t
#define dst_strict_canonicalization_state_init ppc_strict_canonicalization_state_init
#define dst_strict_canonicalization_state_free ppc_strict_canonicalization_state_free
#define dst_insn_get_max_num_imm_operands ppc_insn_get_max_num_imm_operands
#define dst_pc_get_function_name_and_insn_num ppc_pc_get_function_name_and_insn_num
#define DST_FASTCALL_NUM_REGPARAMS PPC_FASTCALL_NUM_REGPARAMS
#define DST_FASTCALL_REGPARAM PPC_FASTCALL_REGPARAM
#define DST_FASTCALL_NUM_RETREGS   PPC_FASTCALL_NUM_RETREGS
#define DST_FASTCALL_RETREG   PPC_FASTCALL_RETREG
#define dst_insn_set_nextpc        ppc_insn_set_nextpc
#define dst_iseq_inv_rename_imms_using_imm_vt_map ppc_iseq_inv_rename_imms_using_imm_vt_map
#define dst_reserved_regs ppc_reserved_regs
#define dst_insn_put_xchg_reg_with_mem ppc_insn_put_xchg_reg_with_mem
#define dst_insn_put_add_imm_with_reg ppc_insn_put_add_imm_with_reg
#define DST_STACK_REGNUM 1
#define dst_callee_save_regs ppc_callee_save_regs
#define dst_iseq_rename_locals_using_locals_map ppc_iseq_rename_locals_using_locals_map
#define dst_iseq_replace_tmap_loc_with_const ppc_iseq_replace_tmap_loc_with_const
#define dst_iseq_rename_randomly_and_assemble ppc_iseq_rename_randomly_and_assemble
#define dst_insn_put_zextend_exreg ppc_insn_put_zextend_exreg
#define dst_emit_translation_marker_insns    ppc_emit_translation_marker_insns
#define dst_iseq_has_marker_prefix           ppc_iseq_has_marker_prefix
#define dst_insn_rename_cregs_to_vregs       ppc_insn_rename_cregs_to_vregs
#define dst_insn_rename_vregs_to_cregs       ppc_insn_rename_vregs_to_cregs
#define dst_enumerate_in_out_transmaps_for_usedef ppc_enumerate_in_out_transmaps_for_usedef
//#define dst_iseq_hash_func_after_canon  ppc_iseq_hash_func_after_canon
#define dst_iseq_convert_peeptab_mem_constants_to_symbols ppc_iseq_convert_peeptab_mem_constants_to_symbols
#define dst_insn_rename_vregs_using_regmap    ppc_insn_rename_vregs_using_regmap
#define dst_opcodes_related    ppc_opcodes_related
#define dst_insn_rename_memory_operand_to_symbol  ppc_insn_rename_memory_operand_to_symbol
#define dst_iseq_count_touched_regs_as_cost ppc_iseq_count_touched_regs_as_cost
#define dst_insn_rename_tag_src_insn_pcs_to_tag_vars ppc_insn_rename_tag_src_insn_pcs_to_tag_vars
#define dst_insn_rename_tag_src_insn_pcs_to_dst_pcrels_using_tinsns_map ppc_insn_rename_tag_src_insn_pcs_to_dst_pcrels_using_tinsns_map
#define dst_insn_is_move_insn                  ppc_insn_is_move_insn
#define dst_insn_rename_defed_reg         ppc_insn_rename_defed_reg
#define dst_iseq_is_well_formed           ppc_iseq_is_well_formed
#define dst_insn_rename_regs               ppc_insn_rename_regs
#define dst_insn_reg_def_is_replaceable    ppc_insn_reg_def_is_replaceable
#define dst_insn_invert_branch_condition   ppc_insn_invert_branch_condition
#define dst_insn_put_function_return       ppc_insn_put_function_return
#define dst_identity_regmap        ppc_identity_regmap

#else
#error "ARCH_DST not specified"
#endif
